- website/package.json
- website/src/components/footer.js
> Add share icons

- src/reducers/vis-state-updaters.js
> bugfix: new filter shouldn't be enlarged if there is already an enlarged filter

- examples/demo-app/src/app.js
- examples/demo-app/src/components/announcement.js
- examples/demo-app/src/components/banner.js
- Remove Autosizer, it causes the page to flick. Adding minHeight didn't help
- banner will show when app loads.
- User can click `close` (It will show again when page refresh)
- User can click `Already took it`. it will forever hide the banner
> [website] add banner to demo app for survey

- package.json
https://github.com/uber/kepler.gl/issues/101
> [Enhancement] remove examples from package files

- src/reducers/composers.js
- src/utils/data-utils.js
- yarn.lock
This PR is to fix issue #125. I've made the following changes:
1. Diff layers by comparing the layer objects
2. Take ALL NEW layers into account when calculating the map bounds
> Consider all new layers when calculating the map bounds

- src/utils/dom-to-image.js
> Fix unable to fetch external stylesheets when taking the screenshot

- src/components/side-panel/panel-header.js
Remove tooltip content and add Share Label on Export button
Resolves #122
> [Enhancement] Add "Share" wording and remove tooltip text on Save/Export button

- README.md
Solve #138 - Include StackOverflow Link on README.md
> [enhancement]Include stackoverflow link in the readme

- README.md
- examples/custom-reducer/package.json
- examples/custom-reducer/src/store.js
- examples/demo-app/package.json
- examples/demo-app/src/store.js
- examples/open-modal/package.json
- examples/open-modal/src/store.js
- package.json
- src/reducers/map-style-updaters.js
- src/reducers/vis-state-updaters.js
- test/node/reducers/map-style-test.js
- website/package.json
- website/src/reducers/index.js
- yarn.lock
Bumps react-palm to the latest version
> Bump react-palm

- src/components/map/map-legend.js
https://github.com/uber/kepler.gl/issues/213
> [bug] fix map legned render error when layer type is not assigned

- src/components/side-panel/layer-panel/layer-configurator.js
- src/deckgl-layers/h3-hexagon-cell-layer/h3-hexagon-cell-layer.js
- src/layers/h3-hexagon-layer/h3-hexagon-layer.js
- src/layers/h3-hexagon-layer/h3-utils.js
- src/layers/layer-factory.js
> [Enhancement] H3 layer: add coverage by value

- src/reducers/vis-state-updaters.js
Combined imports from same file and added missing semicolon.
> Small refactoring of vis-state-updaters

- src/layers/arc-layer/arc-layer.js
Null checks the bounds to stop a potential error from happening
> Null check tBounds & sBounds

- examples/demo-app/src/app.js
- src/components/side-panel/layer-panel/color-range-selector.js
> [bug] sort color steps

- src/processors/data-processor.js
https://github.com/uber/kepler.gl/issues/226
> [bug] fix a bug where field is valid is always false

- package.json
- src/reducers/vis-state-merger.js
- src/schemas/vis-state-schema.js
- test/fixtures/state-saved-v1-4.js
- test/helpers/mock-state.js
- test/node/reducers/vis-state-merger-test.js
- test/node/reducers/vis-state-test.js
- Save textLabel in layer config
- Merge and valid field in textLabel
> [Enhancement] save and load text label config

- src/components/common/logo.js
- src/constants/default-settings.js
https://github.com/uber/kepler.gl/issues/231
> [Enhancement] click kepler.gl logo should go to kepler.gl website

- src/components/map-container.js
Clustered all imports of `props` in one and added MapComponent there in order to create better readability of code.
> [Refactor] Small update of readability

- package.json
- yarn.lock
Move styled-components to devdep from dep & adds peer dep on it, per https://www.styled-components.com/docs/faqs#marking-styledcomponents-as-external-in-your-package-dependencies
Also upgrades styled-comp, no breaking changes indicated in their change log.
> fix issue #264, move styled-components to peer-dep

- package.json
- yarn.lock
Reverts uber/kepler.gl#265.
We need to revert this change for now since we discovered more changes are required!
> Revert "fix issue #264, move styled-components to peer-dep"

- src/components/container.js
- src/components/index.js
- src/components/kepler-gl.js
- src/components/map-container.js
- src/components/side-panel.js
- src/components/side-panel/filter-manager.js
- src/components/side-panel/filter-panel/filter-panel.js
- src/components/side-panel/interaction-manager.js
- src/components/side-panel/interaction-panel/brush-config.js
- src/components/side-panel/interaction-panel/interaction-panel.js
- src/components/side-panel/interaction-panel/tooltip-config.js
- src/components/side-panel/layer-manager.js
- src/components/side-panel/layer-panel/layer-panel.js
- src/components/side-panel/map-manager.js
- src/components/side-panel/map-style-panel/map-layer-selector.js
- src/components/side-panel/map-style-panel/map-style-selector.js
- src/components/side-panel/panel-toggle.js
- src/components/side-panel/side-bar.js
- src/components/side-panel/source-data-catalog.js
Exported
- CollapseButtonFactory
- SidebarFactory
- AddDataButtonFactory
- LayerManagerFactory
- LayerPanelFactory
- SourceDataCatalogFactory
- FilterManagerFactory
- FilterPanelFactory
- InteractionManagerFactory
- BrushConfigFactory
- TooltipConfigFactory
- MapManagerFactory
- LayerGroupSelectorFactory
- MapStyleSelectorFactory
> [Enhancement] Export side panel component factories

- package.json
- src/components/map-container.js
- src/deckgl-layers/sharedstreets-layer/sharedstreets-layer.js
- src/layers/arc-layer/arc-layer.js
- src/layers/base-layer.js
- src/layers/cluster-layer/cluster-layer.js
- src/layers/geojson-layer/geojson-layer.js
- src/layers/grid-layer/grid-layer.js
- src/layers/h3-hexagon-layer/h3-hexagon-layer.js
- src/layers/hexagon-layer/hexagon-layer.js
- src/layers/icon-layer/icon-layer.js
- src/layers/line-layer/line-layer.js
- src/layers/point-layer/point-layer.js
- yarn.lock
- Showing tooltips when hovering over tile layers
> Render pickup/dropoff data with tooltip

- examples/demo-app/src/reducers.js
https://github.com/uber/kepler.gl/issues/287
> [Bug] fix demo-app

- examples/demo-app/package.json
- examples/demo-app/src/actions.js
- examples/demo-app/src/app.js
- examples/demo-app/src/components/load-data-modal/load-data-modal.js
- examples/demo-app/src/components/load-data-modal/sample-data-viewer.js
- examples/demo-app/src/constants/default-settings.js
- examples/demo-app/src/factories/load-data-modal.js
- examples/demo-app/src/main.js
- examples/demo-app/src/reducers.js
- src/actions/vis-state-actions.js
- src/components/kepler-gl.js
- src/components/map-container.js
- src/components/side-panel.js
- src/components/side-panel/layer-manager.js
- src/components/side-panel/source-data-catalog.js
- src/constants/action-types.js
- src/deckgl-layers/sharedstreets-layer/sharedstreets-layer.js
- src/processors/data-processor.js
- src/reducers/vis-state-updaters.js
- src/reducers/vis-state.js
- test/node/reducers/vis-state-test.js
> Add UI to load new Sharedstreets Datasets

- src/components/kepler-gl.js
- src/constants/default-settings.js
https://github.com/uber/kepler.gl/issues/286
https://github.com/uber/kepler.gl/issues/229
https://github.com/uber/kepler.gl/issues/222
https://github.com/uber/kepler.gl/issues/121
> [Enhancement] use mapbox style url for default (published) uber map styles

- src/layers/hexagon-layer/hexagon-layer.js
- src/layers/layer-factory.js
- src/utils/data-utils.js
- render layer hover width based on radius
- hexagon layer radius range set to 0, smaller step
> [Enhancement] Hexbin Layer: smaller radius step and dynamic hover 

- examples/demo-app/package.json
- website/src/reducers/analytics.js
- fix error on track missing payload
> [website] BugFix: missing tracking payload

- src/components/bottom-widget.js
Changed MaxWidth to camelCase maxWidth.
Removed Component from BottomWidget since it does not have an internal state.
Thanks for maintaining this great project!
> [Refactor] Change component to pure function

- examples/demo-app/src/actions.js
- examples/demo-app/src/app.js
- examples/demo-app/src/constants/default-settings.js
- src/components/side-panel/layer-panel/layer-configurator.js
- src/deckgl-layers/sharedstreets-layer/sharedstreets-layer.js
- src/layers/geojson-layer/geojson-layer.js
- src/utils/domain-utils.js
- test/node/index.js
- test/node/utils/domain-utils-test.js
- use the correct domain to calculate accessors in SharedstreetsLayer -- we expand the domain when new data is loaded and call `updateLayerConfig`
> Use the correct domain to calculate accessors in SharedstreetsLayer

- src/reducers/vis-state-updaters.js
> [Typo] Misspellings in comments

- examples/webpack.config.local.js
- src/components/common/info-helper.js
- src/components/side-panel/layer-panel/layer-config-group.js
- Fix webpack local config to import kepler.gl from library src
> [Bug]: fix alias and module resolve in webpack.config.local

- examples/demo-app/src/app.js
- examples/demo-app/src/constants/default-settings.js
- examples/demo-app/src/reducers/index.js
I introduced a new concept of feature flags in demo app.
The app reducer will now inject a new property into demo app.js called __featureFlags__ containing default values defined in default-settings.js. By injecting this property we can turn on and off features
> [Enhancement] Added default feature flags to disable dropbox

- examples/demo-app/src/app.js
We are disabling the current communication banner
> Disable communication banner

- src/components/map-container.js
- src/components/plot-container.js
- src/deckgl-layers/3d-building-layer/3d-building-layer.js
- src/deckgl-layers/3d-building-layer/3d-building-utils.js
- src/utils/dom-to-image.js
- Pass mapbox token from map container to 3d building layer
- Fix image export failure caused by 3d building layer missing mapStyle
- Fix image export failure caused by error reading cssRules from CORS style sheets
>  [Bug] fix 3d building layer missing mapbox token, fix image export

- website/src/content.js
quick fix for doc link in website
> [Bug] Fixed web doc link

- examples/demo-app/index.html
- examples/demo-app/package.json
- examples/demo-app/src/components/load-data-modal/load-data-modal.js
- examples/open-modal/index.html
- examples/umd-client/index.html
- package.json
- src/components/common/styled-components.js
- src/components/modals/export-image-modal.js
- src/utils/dom-to-image.js
- website/package.json
- website/src/static/index.html
- Load uber front css from kepler.gl s3 bucket
- Move Selection Button out from ExportImageModal, it's causing the entire component fail to render on prod due to minification
> [Bug] Fix image export component failed to render

- src/components/common/range-brush.js
- Width change should not trigger this._brush
- Check whether value has changed before triggering props.onBrush
> [Bug] Range slider: correctly setting ranch brush selection when mount

- src/components/common/slider/mouse-event.js
- src/components/common/slider/slider-bar-handle.js
- src/components/common/slider/slider-handle.js
- This is to address MouseEvent movementX property not supported in internet explorer
- A fix for kepler.gl tableau plugin
> [Enhancement] Slider: use clientX to calculate delta to support windows IE and Tableau kepler.gl

- src/components/map-container.js
- src/layers/grid-layer/grid-layer.js
- src/layers/hexagon-layer/hexagon-layer.js
- src/layers/icon-layer/icon-layer.js
- src/layers/point-layer/point-layer.js
https://github.com/uber/kepler.gl/issues/443
> [Bug] Fix points disappear while panning across 180th meridian

- examples/demo-app/src/app.js
- src/deckgl-layers/scatterplot-brushing-layer/scatterplot-brushing-layer.js
- src/layers/aggregation-layer.js
- src/layers/arc-layer/arc-layer.js
- src/layers/base-layer.js
- src/layers/geojson-layer/geojson-layer.js
- src/layers/grid-layer/grid-layer.js
- src/layers/h3-hexagon-layer/h3-hexagon-layer.js
- src/layers/heatmap-layer/heatmap-layer.js
- src/layers/icon-layer/icon-layer.js
- src/layers/point-layer/point-layer.js
- src/reducers/vis-state-merger.js
- src/reducers/vis-state-updaters.js
- src/utils/dataset-utils.js
- src/utils/filter-utils.js
- src/utils/layer-utils/layer-utils.js
- src/utils/utils.js
- test/fixtures/state-saved-v0.js
- test/fixtures/state-saved-v1-1.js
- test/helpers/comparison-utils.js
- test/node/layer-tests/geojson-layer-specs.js
- test/node/layer-tests/grid-layer-specs.js
- test/node/layer-tests/heatmap-layer-specs.js
- test/node/layer-tests/hexagon-layer-specs.js
- test/node/layer-tests/point-layer-specs.js
- test/node/reducers/vis-state-test.js
- test/node/utils/filter-utils-test.js
- test/node/utils/index.js
- test/node/utils/util-test.js
Step. 1 GPU Data filtering feature (https://github.com/uber/kepler.gl/issues/328)
- Add `gpu` property to filter. 
- Implement logic to manage which filter is gpu enabled
- Remove filtered data array from filter result (not used anywhere)
- Implement `set` function to immutably edit reducer state
> [Feat] Gpu data filtering - 1

- examples/demo-app/src/app.js
- src/components/kepler-gl.js
> [Enhancement] expand bottom widget to full length if in read only mode

- src/actions/map-style-actions.js
- src/components/kepler-gl.js
- src/components/modals/export-config-modal.js
- src/constants/action-types.js
- src/reducers/map-style-updaters.js
- src/reducers/map-style.js
- test/browser/components/container-test.js
- test/browser/components/index.js
- test/browser/components/kepler-gl-test.js
- test/node/reducers/map-style-test.js
- Add `requestMapStyles` action
- Consolidate style loading using `getLoadMapStyleTasks` called by `requestMapStyles` and `receiveMapConfg`
- Add tests
> [Enhancement] Cleanup load map style tasks

- src/components/common/file-uploader/file-upload.js
> Removed conditions for file upload handler

- package.json
- src/reducers/map-style-updaters.js
- src/utils/map-style-utils/mapbox-gl-style-editor.js
- test/node/reducers/map-style-test.js
- yarn.lock
> [Enhancement] Fix missing default map styles after loading custom map style from saved json

- src/components/map-container.js
- src/utils/dom-to-image.js
> [Bug] fix image export doesnt get called when map rendered

- README.md
- examples/demo-app/src/app.js
- src/components/kepler-gl.js
- src/components/map-container.js
Matching deck.gl's [`onViewStateChange`](https://deck.gl/#/documentation/deckgl-api-reference/deck?section=onviewstatechange-function-) Function
> [Feat] add onViewStateChange callback to KeplerGl

- src/components/side-panel/layer-manager.js
This diff will fix the drag and drop issue when sorting current layers.
> [Bug] Fixed layer list sorting dnd effect

- src/components/kepler-gl.js
- src/components/side-panel.js
- src/connect/keplergl-connect.js
- src/constants/user-guides.js
- Use reselect to select and merge user-defined action creators
- Wrap mapDispatchToProps in a factory function, so each instance of Kepler will have its own selector
> [Bug] fix side panel unnecessary rerender

- README.md
- docs/user-guides/k-save-and-export.md
- examples/custom-reducer/src/store.js
- examples/custom-theme/src/store.js
- examples/demo-app/package.json
- examples/demo-app/src/components/load-data-modal/load-data-modal.js
- examples/demo-app/src/components/sharing/cloud-tile.js
- examples/demo-app/src/store.js
- examples/open-modal/src/store.js
- examples/replace-component/src/store.js
- examples/umd-client/index.html
- package.json
- src/components/common/file-uploader/file-upload.js
- src/components/common/modal.js
- src/components/common/styled-components.js
- src/components/modal-container.js
- src/components/modals/add-map-style-modal.js
- src/components/modals/data-table-modal.js
- src/components/side-panel/layer-panel/layer-configurator.js
- src/styles/base.js
- src/styles/media-breakpoints.js
- src/templates/export-map.js
- test/helpers/mock-state.js
- test/node/reducers/map-style-test.js
- test/node/reducers/vis-state-merger-test.js
- test/node/schemas/map-state-schema-test.js
- test/node/schemas/map-style-schema-test.js
- test/node/schemas/vis-state-schema-test.js
- website/src/static/index.html
- yarn.lock
This pull request will implement responsive style for application modal dialogs.
The modal dialog layout and style will change accordingly with the browser size.
The modal dialog content is now scrollable to ensure visibility on smaller devices and browser windows.
> [Enhancement] Refactored modal dialog to be more responsive

- website/webpack.config.js
Minified code in netlify was triggering an __undefined module__(Deck.gl) error.
> Netlify webpack optimization

- src/components/side-panel/layer-panel/layer-configurator.js
I guess the right prop is type?
> Fix typo on layer-configurator.js

- examples/demo-app/src/app.js
- src/components/map/map-control.js
- src/components/map/map-legend.js
- src/layers/base-layer.js
- src/layers/geojson-layer/geojson-layer.js
- src/layers/point-layer/point-layer.js
- src/utils/utils.js
- test/browser/components/map/index.js
- test/browser/components/map/map-legend-test.js
- test/helpers/component-utils.js
- Handle cases when layer has more than 1 color channel
#531
> [Bug] Display color legend for stroke color scale

- docs/user-guides/a-introduction.md
- docs/user-guides/c-types-of-layers/e-geojson.md
- docs/user-guides/c-types-of-layers/e-polygon.md
- docs/user-guides/c-types-of-layers/h-hexbin.md
- docs/user-guides/c-types-of-layers/i-heatmap.md
- docs/user-guides/c-types-of-layers/j-h3.md
- Add hex bin, heat map, h3 layer to documentation
- Change geojson layer to polygon layer
> [Docs] update user documentation with newer layers and features

- docs/user-guides/b-kepler-gl-workflow/a-add-data-to-the-map.md
- docs/user-guides/b-kepler-gl-workflow/b-add-data-layers/a-adding-data-layers.md
- docs/user-guides/c-types-of-layers.md
- docs/user-guides/c-types-of-layers/a-point.md
- docs/user-guides/c-types-of-layers/j-h3.md
- docs/user-guides/f-map-styles/1-base-map-styles.md
- docs/user-guides/j-get-started.md
- docs/user-guides/k-save-and-export.md
Added load map using url section, adding more docs about each layer type, 3d building layer
> [Docs] Updating Layer User Guides

- package.json
remove yarn since netlify run yarn by default
> Update build command to netlify pull request builds

- bindings/kepler.gl-jupyter/keplergl/keplergl.py
The parenthesis-less print failed KeplerGl object initialization.
> Fixed python3 compatibility and wrong variable in string format

- src/components/common/range-plot.js
- src/styles/base.js
https://github.com/keplergl/kepler.gl/issues/603
> [Enhancement] Use theme in histogram plot color

- src/components/map-container.js
- src/components/plot-container.js
> [Bug] add deckGlProps to pass preserveDrawingBuffer to plot container

- src/layers/point-layer/point-layer.js
__Before__
__After__
https://github.com/keplergl/kepler.gl/issues/614
> [Bug] Don't show null for labels if there is no data

- src/deckgl-layers/3d-building-layer/3d-building-layer.js
> [Bug] Fix 3d building layer crashing

- examples/custom-reducer/index.html
- examples/custom-theme/index.html
- examples/demo-app/index.html
- examples/open-modal/index.html
- examples/replace-component/index.html
- examples/umd-client/index.html
- src/templates/export-map.js
- website/src/static/index.html
> [Enhancement] Update mapbox-gl css version

- src/actions/map-style-actions.js
- src/components/map-container.js
- src/components/side-panel.js
- src/components/side-panel/map-manager.js
- src/constants/action-types.js
- src/deckgl-layers/3d-building-layer/3d-building-layer.js
- src/reducers/map-style-updaters.js
- src/reducers/map-style.js
- src/schemas/map-style-schema.js
- test/helpers/mock-state.js
- test/node/reducers/map-style-test.js
- test/node/reducers/root-test.js
- test/node/schemas/map-style-schema-test.js
> [Enhancement] Add 3d building color editor

- README.md
Added netlify badge to readme page
Implements: #639
> Netlify badge

- .travis.yml
Using xvfb as a service:
https://benlimmer.com/2019/01/14/travis-ci-xvfb/
> [Chore] use xvfb as a service in travis-ci

- src/components/plot-container.js
- src/utils/dom-to-image.js
> [Enhancement] pass set useDevicePixels to deck.gl to plot container

- src/components/common/datagrid.js
- src/components/modals/data-table-modal.js
- src/styles/base.js
- src/utils/data-utils.js
- test/browser/components/data-table-modal-test.js
Fixes #679 
The current implementation doesn't have the ability to display a subset of the row properties so I had to create a way to omit some of the properties.
> [Bug] Fixed issue with geojson fields

- docs/user-guides/c-types-of-layers/k.trip.md
- src/components/common/animation-control/animation-slider.js
- src/components/common/animation-control/speed-control.js
- src/layers/trip-layer/trip-info-modal.js
- src/layers/trip-layer/trip-layer.js
- src/reducers/vis-state-updaters.js
- Add info icon on how to format data for trip layer in side panel
- New slider ui with animated timestamp and start/end time displayed
#397
> [FEAT] Add trip layer - 3

- examples/demo-app/src/app.js
- examples/demo-app/src/data/sample-trip-data.js
- src/layers/heatmap-layer/heatmap-layer.js
- test/node/layer-tests/heatmap-layer-specs.js
> [Bug] fix heatmap getBounds

- package.json
- locking luma and deck resulting in 2 versions of luma being installed
- unlock luma to relax on the version
> [Bug] Unlock luma

- examples/custom-reducer/package.json
- examples/custom-theme/package.json
- examples/demo-app/package.json
- examples/open-modal/package.json
- examples/replace-component/package.json
- examples/umd-client/index.html
- package.json
- scripts/edit-version.js
- Add a script to edit example kepler.gl version
> [Chore] Add a script to automatically edit kepler.gl version

- examples/node-app/.babelrc
- examples/node-app/README.md
- examples/node-app/index.html
- examples/node-app/package.json
- examples/node-app/server.js
- examples/node-app/src/app-reducer.js
- examples/node-app/src/app.js
- examples/node-app/src/main.js
- examples/node-app/src/store.js
- examples/node-app/webpack.config.js
- package.json
- yarn.lock
This PR implements a Kepler.gl example using: Express, Webpack #664
> [Enhancement] Express example

- README.md
- src/actions/map-style-actions.js
- src/components/kepler-gl.js
- src/components/modals/add-map-style-modal.js
- src/components/modals/export-map-modal.js
- src/constants/default-settings.js
- src/layers/trip-layer/trip-layer.js
- src/reducers/map-style-updaters.js
- src/utils/map-style-utils/mapbox-gl-style-editor.js
- test/browser/components/container-test.js
- test/helpers/mock-state.js
- test/node/reducers/map-style-test.js
- test/node/schemas/map-style-schema-test.js
- generate custom map style icon from style url
- move DEFAULT_MAPBOX_API_URL to default settings 
- pass mapboxApiUrl to add-map-style-modal
- update README
> [Enhancement] Custom map style icon

- examples/demo-app/package.json
- examples/demo-app/src/app.js
- examples/demo-app/src/components/map-control/map-control.js
- examples/demo-app/src/factories/map-control.js
- examples/demo-app/src/reducers/index.js
- src/components/common/icons/code-alt.js
- src/components/common/modal.js
- src/components/common/styled-components.js
- src/components/map/map-control.js
- Add a panel in the demo app to display sample map details and link to data and config json
> [Enhancement] Demo app sample info

- src/reducers/combined-updaters.js
- test/node/reducers/composer-state-test.js
> [Bug] fix readonly in addDataToMap

- src/components/common/file-uploader/file-upload.js
- src/constants/user-guides.js
> [Enhancement] add file format instruction to file upload

- bindings/kepler.gl-jupyter/RELEASE.md
- bindings/kepler.gl-jupyter/js/lib/keplergl/kepler.gl.js
- bindings/kepler.gl-jupyter/js/package.json
- bindings/kepler.gl-jupyter/keplergl/_version.py
- bindings/kepler.gl-jupyter/notebooks/DataFrame.ipynb
- upgrade kepler.gl to 1.1.9
- set centerMap to false if mapState exist
> [Jupyter] Publish keplergl jupyter 0.1.2

- docs/user-guides/b-kepler-gl-workflow/a-add-data-to-the-map.md
Just found them reading the docs, hope it's helpful!
> [DOCS] Fix some typos in add-data-workflow-user-guide

- src/layers/geojson-layer/geojson-utils.js
- src/layers/trip-layer/trip-utils.js
- test/fixtures/test-csv-data.js
- test/node/layer-tests/geojson-layer-specs.js
- test/node/utils/layer-utils-test.js
> [Bug] fix empty geometry causing trip layer detection to fail, add tests

- .github/workflows/npmpublish.yml
This PR will implement github action to publish Kepler.gl to npm and gpr once a new release is created
> [Feat] Github action to publish npm package

- src/components/bottom-widget.js
- src/components/filters/time-widget.js
- src/components/modals/delete-data-modal.js
- src/reducers/vis-state-updaters.js
- test/node/reducers/vis-state-test.js
Fixed issue when deleting dataset.
> [Bug] Fixed delete dataset action

- src/components/common/item-selector/typeahead.js
- src/reducers/vis-state-merger.js
- src/reducers/vis-state-updaters.js
- src/utils/filter-utils.js
- test/node/reducers/vis-state-test.js
- reset filter domain when update filter name
> [Bug] Don't merge domain when update filter name

- src/components/modals/export-map-modal/components.js
- src/components/modals/export-map-modal/export-html-map.js
- src/components/modals/export-map-modal/export-json-map.js
- src/components/modals/modal-dialog.js
- test/node/layer-tests/cluster-layer-specs.js
- website-gatsby/gatsby-browser.js
- website-gatsby/gatsby-node.js
- website-gatsby/gatsby-ssr.js
- website-gatsby/src/state/index.js
- website-gatsby/src/state/redux-wrapper.js
- website-gatsby/src/state/test.js
Added licence content to files
> [Bug] Added license to exportmap files, modal dialog and gatsby

- examples/custom-reducer/package.json
- examples/custom-reducer/webpack.config.js
- examples/custom-theme/package.json
- examples/custom-theme/webpack.config.js
- examples/demo-app/package.json
- examples/demo-app/webpack.config.js
- examples/node-app/package.json
- examples/node-app/webpack.config.js
- examples/open-modal/package.json
- examples/open-modal/webpack.config.js
- examples/replace-component/package.json
- examples/webpack.config.local.js
- website/package.json
> [Bug] fix demo-app resolve react-redux

- src/layers/geojson-layer/geojson-layer.js
- src/processors/data-processor.js
- src/schemas/dataset-schema.js
- test/fixtures/geojson.js
- test/fixtures/state-saved-v0.js
- test/fixtures/state-saved-v1-1.js
- test/fixtures/state-saved-v1-2.js
- test/fixtures/state-saved-v1-3.js
- test/fixtures/state-saved-v1-4.js
- test/fixtures/test-csv-data.js
- test/fixtures/test-hex-id-data.js
- test/helpers/mock-state.js
- test/node/reducers/vis-state-test.js
- test/node/utils/data-processor-test.js
- test/node/utils/layer-utils-test.js
- add `analyzerType` to field analyze output
- check `analyzerType` in GeojsonLayer.findDefaultLayer method
> [Bug] Fix multiple geojson layer found when properties contain object and array

- src/reducers/vis-state-updaters.js
> Fix newDateEntries typo and formatting fixes

- package.json
- src/processors/data-processor.js
- test/fixtures/state-saved-v1-2.js
- test/node/schemas/dataset-schema-test.js
- test/node/utils/data-processor-test.js
addresses https://github.com/keplergl/kepler.gl/issues/839
> treat numbers as strings

- docs/api-reference/cloud-providers/overview.md
Initial stub for cloud provider docs
> docs: cloud provider api

- src/components/index.js
> (bugfix) Correct ModalDialogFactory export name

- UPGRADE-GUIDE.md
> [Docs] add Upgrade-guide

- README.md
- docs/api-reference/actions/actions.md
- docs/api-reference/get-started.md
> Update grammar, cleanup whitespace, fix broken link

- src/templates/export-map-html.js
- Assign centerMap: false in exported html
> [Fix] mapState not applied in exported map html

- CHANGELOG.md
- examples/custom-reducer/package.json
- examples/custom-theme/package.json
- examples/demo-app/package.json
- examples/node-app/package.json
- examples/open-modal/package.json
- examples/replace-component/package.json
- examples/umd-client/index.html
- package.json
> Version 1.1.13

- .github/workflows/npmpublish.yml
This PR removes action to publish kepler to github package repository
> [Chore] remove action to publish to github package repo

- src/templates/export-map-html.js
> [Enhancement] Hide data modal in export map

- src/actions/actions.js
Per comments on https://github.com/keplergl/kepler.gl/pull/912
> (chore) Correctly update the copy changes to actions.js

- package.json
- test/fixtures/state-saved-v1-2.js
- test/node/schemas/dataset-schema-test.js
- yarn.lock
> [Bug] Fix mix int/float column interpreted as sting

- examples/demo-app/src/store.js
> [Bug] do not add redux devtools in demo app by default

- src/layers/heatmap-layer/heatmap-layer.js
- src/layers/mapboxgl-layer.js
- test/browser/layer-tests/heatmap-layer-specs.js
- test/fixtures/test-csv-data.js
- do not assign mapbox style filter when there is none
> [Bug] fix heatmap not displayed when there is no filter

- src/components/map/layer-hover-info.js
- src/layers/geojson-layer/geojson-layer.js
- src/layers/h3-hexagon-layer/h3-hexagon-layer.js
- src/layers/hexagon-layer/hexagon-layer.js
> [Bug] fix hexagon layer hover cause app crash

- src/components/modal-container.js
- src/utils/export-utils.js
- test/node/reducers/composer-state-test.js
- test/node/utils/export-utils-test.js
- test/node/utils/index.js
> [Bug] Fixed json map export and added tests

- src/layers/aggregation-layer.js
- src/layers/hexagon-layer/hexagon-layer.js
- src/layers/hexagon-layer/hexagon-utils.js
- test/browser/layer-tests/heatmap-layer-specs.js
- test/browser/layer-tests/hexagon-layer-specs.js
- test/node/utils/export-utils-test.js
> [Bug] fix hexagon layer hover crash

- examples/demo-app/src/store.js
- src/components/filters/filter-panels/filter-panel-with-field-select.js
- src/components/side-panel.js
- src/components/side-panel/filter-panel/filter-panel.js
- src/components/side-panel/panel-header.js
- src/layers/aggregation-layer.js
- test/node/reducers/vis-state-test.js
This PR fixes a crash when trying to create a filter and choosing among different datasets
> [Bug] Select dataset filter bug

- package.json
- yarn.lock
- handle single line function composition
> [Style] upgrade prettier to 1.19

- src/components/common/checkbox.js
- src/styles/base.js
Fixes https://github.com/keplergl/kepler.gl/issues/972
**Before:**
**After:**
> [Bug] Fix text collision on toggle input

- .github/workflows/npmpublish.yml
> [Chore] Removed testing from publish action

- src/reducers/ui-state-updaters.js
> [Bugfix] Fix typo on variable name

- package.json
> [Bug] add cloud-providers.js to package.json

- examples/demo-app/package.json
- examples/demo-app/src/actions.js
- examples/demo-app/src/cloud-providers/carto/carto-provider.js
> [Bug] Fix username set to null after loading map from URL

- README.md
- docs/api-reference/custom-theme/overview.md
- examples/demo-app/src/app.js
- src/components/common/field-selector.js
- src/components/common/logo.js
- src/components/common/styled-components.js
- src/components/kepler-gl.js
- src/components/side-panel/common/dataset-title.js
- src/components/side-panel/layer-panel/layer-panel-header.js
- src/components/side-panel/panel-header.js
- src/constants/default-settings.js
- src/styles/base.js
- Add base web theme as additional theme
> [Enhancement] Add more light themes

- test/node/reducers/provider-state-test.js
> [Bug] fix provider tests

- src/constants/default-settings.js
- test/browser/components/kepler-gl-test.js
> [Feat] Add satellite basemap

- examples/demo-app/src/cloud-providers/carto/carto-provider.js
> Fixed carto-provider example

- src/processors/index.js
https://github.com/keplergl/kepler.gl/issues/1021
> [Bug] export formatCsv

- examples/demo-app/src/app.js
- src/components/index.js
- src/components/side-panel/layer-panel/layer-panel-header.js
- src/components/side-panel/layer-panel/layer-panel.js
- src/components/side-panel/panel-header-action.js
- test/browser/components/side-panel/index.js
- test/browser/components/side-panel/layer-panel-header-test.js
- Move eye to the end
- Make layer panel header a factory
> [Enhancement] Move layer panel visible toggle to end

- src/components/side-panel/layer-panel/layer-configurator.js
- src/layers/point-layer/point-layer.js
> [Bug] fix scatterplot stroke width to pixels

- src/utils/data-utils.js
> [Bugfix] Remove incorrect outlier calculation for better map centering

- src/components/common/item-selector/keyevent.js
- src/components/common/styled-components.js
- src/components/index.js
- src/components/side-panel/filter-manager.js
- src/components/side-panel/layer-manager.js
- src/components/side-panel/map-manager.js
> [Enhancement] add classes to button for easier style override

- examples/custom-reducer/package.json
- examples/custom-theme/package.json
- examples/demo-app/package.json
- examples/node-app/package.json
- examples/open-modal/package.json
- examples/replace-component/package.json
- examples/umd-client/index.html
- src/templates/export-map-html.js
> [Chore] Updated example to 2.1.0

- examples/custom-reducer/package.json
- examples/custom-theme/package.json
- examples/demo-app/package.json
- examples/node-app/package.json
- examples/open-modal/package.json
- examples/replace-component/package.json
- examples/umd-client/index.html
> Updated examples to v2.1.1

- src/styles/base.js
> [Chore] Improve the secondary button color for base theme

- package.json
> [Chore] Removed engine requirements

- examples/demo-app/package.json
- examples/demo-app/src/cloud-providers/carto/carto-provider.js
Hi, this is a small fix to deal in a proper way with case sensitive fields in CARTO provider.
> Fixes for case sensitive fields in CARTO storage

- UPGRADE-GUIDE.md
> [Docs] update upgrade guide

- docs/user-guides/h-playback.md
- docs/user-guides/j-get-started.md
> [Doc] Update playback documentation

- contributing/DEVELOPERS.md
> [Doc] Updated release docs with gh-release instructions

- src/components/editor/editor.js
- src/components/editor/feature-action-panel.js
- src/components/index.js
- src/components/map-container.js
- test/browser/components/editor/feature-action-panel-test.js
> [Enhancement] Added Editor and FeatureActionPanel factories

- src/components/common/styled-components.js
- src/components/kepler-gl.js
- src/components/map-container.js
- src/reducers/combined-updaters.js
> [Enhancement] use original mapbox attribute color, smaller font

- bindings/kepler.gl-jupyter/js/.gitignore
- bindings/kepler.gl-jupyter/js/lib/keplergl/components/config-panel.js
> fix gitignore in jupyter

- src/components/side-panel.js
> add side-panel inner class

- docs/RFC/table-class.md
- src/utils/dataset-utils.js
> [RFC] table class RFC

- src/layers/trip-layer/trip-utils.js
- test/browser/layer-tests/trip-layer-specs.js
> [Enhancement] filter invalid value when calculate trip layer domain

- src/components/bottom-widget.js
- src/components/common/animation-control/animation-speed-slider.js
- src/components/common/animation-control/speed-control.js
- src/components/common/item-selector/dropdown-list.js
- src/components/common/item-selector/item-selector.js
- src/components/common/range-plot.js
- src/components/common/range-slider.js
- src/components/common/time-range-slider.js
- src/components/filters/range-filter.js
- src/components/filters/time-range-filter.js
- src/components/index.js
- src/components/kepler-gl.js
- src/components/side-panel/interaction-panel/brush-config.js
- src/components/side-panel/layer-panel/layer-configurator.js
- src/components/side-panel/layer-panel/text-label-panel.js
- src/components/side-panel/layer-panel/vis-config-slider.js
- src/constants/index.js
- src/styles/base.js
create and export time widget factories
-RangeSliderFactory 
-VisConfigSliderFactory 
-TextLabelPanelFactory 
-RangeFilterFactory 
-AnimationSpeedSliderFactory 
-RangePlotFactory
> [Enhancement] Export time widget factories

- src/components/common/item-selector/typeahead.js
- src/components/editor/editor.js
- src/components/map/map-popover.js
- src/components/modal-container.js
- src/constants/keyevent.js
> [Enhancement] close modal when press escape key

- examples/demo-app/src/app.js
- examples/demo-app/src/components/announcement.js
- examples/demo-app/src/components/banner.js
- test/browser/layer-tests/trip-layer-specs.js
- website/src/components/home.js
New banner and link
Signed-off-by: Giuseppe Macri <mari.giuseppe@gmail.com>
> Added new banner link

- website/package.json
- website/webpack.config.js
> [website] remove unused env, relax on  package engines requirement

- src/components/common/animation-control/animation-speed-slider.js
- src/constants/default-settings.js
> [Enhancement] speed control step to 0.001

- src/components/index.js
- src/components/side-panel/layer-panel/layer-config-group.js
- src/components/side-panel/layer-panel/layer-panel.js
- src/components/side-panel/layer-panel/layer-type-selector.js
- src/styles/base.js
> [Enhancement] export more layer configurator components

- src/actions/actions.d.ts
- src/actions/vis-state-actions.d.ts
- src/components/common/image-preview.js
- src/components/modal-container.d.ts
- src/components/modal-container.js
- src/processors/file-handler.d.ts
- src/reducers/combined-updaters.d.ts
- src/reducers/ui-state-updaters.d.ts
And this PR activates component type checking against the existing State and Action types (which was the goal with last couple of PRs).
> Enable Modal types #2 of 2

- src/components/common/file-uploader/file-upload.d.ts
- src/components/common/file-uploader/file-upload.js
- src/components/modal-container.js
- src/components/modals/load-data-modal.d.ts
- src/reducers/vis-state-selectors.js
Signed-off-by: Ib Green <ib@unfolded.ai>
> Add prop to disable file extension checking

- bindings/kepler.gl-jupyter/keplergl/keplergl.py
Signed-off-by: sangarshanan <sangarshanan1998@gmail.com>
Closes #1200
> Convert to gdf to a dataframe instead of a copy

- examples/replace-component/README.md
Signed-off-by: Varun Dey <varundey20@gmail.com>
> Fix `replace-component` Readme

- src/components/kepler-gl.js
> [Enhancement] Render geocode in readOnly mode if enabled

- src/components/kepler-gl.js
- src/components/map-container.js
- add `onDeckInitialized` to KeplerGl comp prop
- add `deckGlProps` to KeplerGl comp prop
> [Enhancement] Add KeplerGl.onDeckInitialized callback

- examples/webpack.config.local.js
- src/actions/actions.d.ts
- src/actions/actions.js
- src/reducers/combined-updaters.js
- src/reducers/vis-state-updaters.js
- test/node/reducers/composer-state-test.js
> [Enhancement] add options.autoCreateLayers to addDataToMap

- package.json
- src/components/common/field-selector.js
- src/components/common/item-selector/item-selector.js
- src/components/geocoder-panel.js
- src/components/side-panel/interaction-panel/tooltip-config.js
- src/components/side-panel/interaction-panel/tooltip-config/tooltip-chicklet.js
- src/constants/default-settings.js
- src/constants/tooltip.js
- src/utils/data-utils.js
- test/browser/components/tooltip-config-test.js
- test/node/utils/data-utils-test.js
> [Bug] fix tooltip config, add boolean formatter

- src/layers/h3-hexagon-layer/h3-hexagon-layer.js
- src/layers/h3-hexagon-layer/h3-utils.js
- src/utils/index.js
- src/utils/layer-utils.js
> [Feat] Auto detect h3 layer from h3 field data (#53)

- src/components/geocoder/geocoder.js
- src/components/plot-container.js
- test/browser/index.js
- yarn.lock
> [Bug] Fixed image export bug due to mapbox attrition logo

- examples/demo-app/src/app.js
- src/utils/split-map-utils.js
- website/src/components/home.js
> [Website] disable banner

- examples/custom-reducer/package.json
- examples/custom-theme/package.json
- examples/demo-app/package.json
- examples/node-app/package.json
- examples/open-modal/package.json
- examples/replace-component/package.json
- package.json
- yarn.lock
> [Enhancement] upgrade react-palm to 3.3.6

- src/components/modals/export-image-modal.js
- test/browser/components/modals/export-image-modal-test.js
- test/browser/components/modals/index.js
> [Bug] fix export image size not set

- src/components/common/field-token.js
- src/styles/base.js
> [Bug] fix dropdown list item line height

- src/components/common/checkbox.js
- src/styles/base.js
> [Enhancement] switch style tweak

- src/components/common/item-selector/item-selector.js
- src/components/index.js
This PR is about exporting StyledDropdownSelect to the make it available for further uses
> Export StyledDropdownSelect

- src/components/side-panel/filter-manager.js
- test/browser/components/side-panel/filter-manager-test.js
- test/browser/components/side-panel/index.js
> [Enhancement] render last added filter first

- examples/demo-app/src/components/load-data-modal/load-remote-map.js
- src/components/common/checkbox.js
- src/components/common/field-selector.js
- src/components/common/info-helper.js
- src/components/common/item-selector/item-selector.js
- src/components/common/item-selector/typeahead.js
- src/components/common/map-layer-selector.js
- src/components/index.js
- src/components/modals/data-table-modal.js
- src/styles/base.js
- src/utils/dataset-utils.d.ts
- src/utils/index.js
- light them fix in typeahead
- Show arrow in dropdown select
- Add radio button style
- Add showTab prop to data table modal
> [Enhancement] UI input style improvement

- src/reducers/vis-state-updaters.js
> [Bug] Fixed bug when reversing color schema

- src/components/map-container.js
- test/node/utils/index.js
- test/node/utils/map-info-utils-test.js
> [Bug] Check for valid layer pinned prop before performing comparison

- src/components/common/item-selector/item-selector.js
- src/components/common/time-slider-marker.js
- src/styles/base.js
this change is needed for the light theme
> Add inputBGdActive for light theme

- src/components/common/item-selector/item-selector.js
- src/layers/h3-hexagon-layer/h3-hexagon-layer.js
- src/layers/h3-hexagon-layer/h3-utils.js
* Use only hex field to create h3 layer
> [Bug] avoid duplicated h3 layer detection (#93)

- src/components/common/item-selector/item-selector.js
- src/utils/data-utils.d.ts
- src/utils/index.js
> [Chores] Exported default formatters (#92)

- src/components/common/item-selector/item-selector.js
- src/components/map/map-popover.js
> [Enhancement] fix item-selector dropdown value overflow nad tooltip pin color

- src/components/common/checkbox.js
- src/styles/base.js
> [Enhancement] fix radio button style

- src/components/index.js
- src/components/side-panel/layer-panel/layer-configurator.js
- src/components/side-panel/layer-panel/vis-config-switch.js
> [Enhancement] make visConfigSwitch a factory 

- src/processors/data-processor.js
> [Bug] check category

- src/localization/ca.js
- src/localization/es.js
Added missing spanish and catalan translations (some new features from last translation update)
> update spanish and catalan translations

- src/constants/index.js
- src/utils/index.js
CHORE: KeyEvent export
CHORE: Additional export-utils exports
> [Chore] Export KeyEvent and  downloadFile utils

- src/components/index.js
- src/styles/base.js
> [Enhancement] Adjust input light styles

- src/components/common/data-table/index.js
- src/layers/index.d.ts
- src/reducers/core.d.ts
- src/reducers/core.js
- src/reducers/vis-state-merger.d.ts
- src/reducers/vis-state-merger.js
- src/reducers/vis-state-updaters.d.ts
- src/reducers/vis-state-updaters.js
- src/schemas/index.d.ts
- src/schemas/schema-manager.d.ts
- src/utils/dataset-utils.js
- src/utils/filter-utils.d.ts
- src/utils/filter-utils.js
- src/utils/index.js
- src/utils/layer-utils.js
- test/browser.js
- test/fixtures/test-trip-data.js
- test/node/reducers/vis-state-merger-test.js
* extract valdiate layer and validate filter function and export them
> [Enhanment] extract valdiate layer and validate filter function

- src/components/common/data-table/index.js
- src/layers/base-layer.js
- src/layers/layer-text-label.js
- src/utils/dataset-utils.js
> [Enhancement] added check for oldLayerData

- src/components/common/styled-components.js
- src/styles/base.js
> [Enhancement] Fix negative button border

- src/components/index.js
- src/components/side-panel/layer-panel/column-selector.js
- src/localization/ca.js
- src/localization/es.js
- src/processors/index.js
- src/utils/layer-utils.js
- test/node/utils/layer-utils-test.js
> [Enhancement] better arc layer column config layout

- src/components/side-panel/layer-panel/color-selector.js
- src/components/side-panel/layer-panel/custom-palette.js
> [Bug] Fixed color picker closure when selecting first custom palette value

- src/components/side-panel.js
- src/reducers/ui-state-updaters.d.ts
- src/reducers/ui-state-updaters.js
- src/reducers/ui-state.js
> [enhancement]: Add uiStateshowDatasetTableto intercept showDatasetTable action

- src/components/bottom-widget.js
- src/reducers/vis-state-updaters.d.ts
- src/utils/filter-utils.d.ts
- src/utils/filter-utils.js
- src/utils/index.js
- test/node/utils/filter-utils-test.js
> [Bug] Added better check for bins in bottom widget

- package.json
- src/components/map/coordinate-info.js
- src/components/map/map-popover.js
- test/browser/components/map/map-popover-test.js
- yarn.lock
> [Enhancement] avoid calling mapPopover setstate infinitely

- src/components/map/map-popover.js
- src/components/side-panel/layer-panel/layer-configurator.js
> [Bug] fix arc layer configurator crash

- src/components/common/animation-control/playback-controls.js
- src/processors/index.js
Signed-off-by: Nicolas Rojo <nicolas.martin.rojo@gmail.com>
> [Bug] Fix speed button input on timeline

- src/constants/tooltip.js
- test/node/utils/data-utils-test.js
Signed-off-by: Valentine <vpanchin@gmail.com>
> [Feat] fixed augumented numeric formats with ~

- src/utils/layer-utils.js
> [Bug]: FIxed issue with map popover object being null

- src/schemas/schema-manager.d.ts
- src/schemas/vis-state-schema.js
- test/fixtures/test-csv-data.js
- test/helpers/mock-state.js
- test/node/schemas/vis-state-schema-test.js
> [Feat]: Export filter speed to schema

- src/components/kepler-gl.js
- add position relotive, height and width to global style
> [Bug] Add style prop to kepler-gl container

- src/components/common/item-selector/chickleted-input.js
- src/components/common/item-selector/item-selector.js
- src/components/filters/filter-panels/filter-panel-with-field-select.js
- src/layers/layer-factory.d.ts
- src/reducers/vis-state-updaters.js
- src/utils/filter-utils.js
- src/utils/layer-utils.js
- test/fixtures/test-hex-id-data.js
- test/node/reducers/vis-state-merger-test.js
- test/node/reducers/vis-state-test.js
> [Enhancement] add changedFilters to datasets when filter data is called

- src/components/common/animation-control/animation-controller.js
- test/node/utils/data-utils-test.js
* Fix: If time series speed is set to 0, the timeline should stop animation (Step by interval mode)
* Added tests for clamp
> [Bug] Interval animation doesn't stop when speed is set to 0

- src/processors/index.js
Signed-off-by: Wesam Manassra <wesam.manassra@gmail.com>
> CHORE: export processKeplerglDataset

- src/components/side-panel/panel-toggle.js
- src/reducers/vis-state-updaters.js
- test/node/reducers/vis-state-test.js
> [Bug] fix update dataId not update layer data

- src/components/common/range-brush.js
> [Bug]: Fixed range slider null selection bug

- src/components/index.js
- src/components/side-panel/panel-toggle.js
> [Enhancement] make panel tab a factory

- README.md
- docs/api-reference/README.md
- docs/api-reference/advanced-usages/custom-map-styles.md
- examples/README.md
- examples/custom-map-style/.babelrc
- examples/custom-map-style/README.md
- examples/custom-map-style/index.html
- examples/custom-map-style/package.json
- examples/custom-map-style/src/app.js
- examples/custom-map-style/src/main.js
- examples/custom-map-style/src/store.js
- examples/custom-map-style/webpack.config.js
- package.json
- src/components/modals/add-map-style-modal.js
- src/components/side-panel/map-manager.js
- src/localization/ca.js
- src/localization/en.js
- src/utils/map-style-utils/mapbox-gl-style-editor.js
> [Doc] Add example using none mapbox base map

- docs/user-guides/h-playback.md
Signed-off-by: Eric Pan <epan@users.noreply.github.com>
> [Doc] Fix typos on playback readme

- package.json
Signed-off-by: Map1en_ <maplenagisa@gmail.com>
> [Chore] Move 'uber-licence' to devDep

- docs/api-reference/localization/README.md
- src/localization/ja.js
- src/localization/locales.js
I've added a new language "Japanese" (ja), following the documentation below:
https://github.com/keplergl/kepler.gl/tree/master/docs/api-reference/localization
> [Enhancement] add Japanese translation

- src/components/side-panel/layer-panel/layer-configurator.js
> [Bug] fix arc layer configurator render crash

- src/components/common/action-panel.js
- src/components/editor/editor.js
- src/components/editor/feature-action-panel.js
- src/localization/en.js
- test/browser/components/editor/feature-action-panel-test.js
- Right click on a feature shows the option panel
- Add copy geometry option
> [Feature]: add copy geometry to feature action panel

- website/.babelrc
- website/src/components/common/styled-components.js
- website/src/components/ecosystems.js
- website/src/components/hero.js
- website/src/components/home.js
- website/src/constants.js
- website/src/content.js
- website/src/utils.js
- website/webpack.config.js
> [Website] Add ecosystem

- src/processors/data-processor.js
> [Bug] trim string value before passing to type analyzer

- website/src/content.js
@heshan0131 I left plugin title as is.
> [Website] Update GeoDataViewer github url and description (#1524)

- bindings/kepler.gl-jupyter/js/README.md
- bindings/kepler.gl-jupyter/js/lib/keplergl/components/app.js
- bindings/kepler.gl-jupyter/keplergl/_version.py
> [Jupyter] Update jupyter widget, release kepler.gl-jupyter@0.3.0

- docs/api-reference/localization/README.md
- examples/demo-app/src/constants/localization.js
- src/localization/cn.js
- src/localization/locales.js
Add Chinese (Simplified) translation to promote internationalization.
> [Enhancement] Add Chinese (Simplified) translation

- src/components/map-container.js
PR to address the DeckGLProps layers issue: https://github.com/keplergl/kepler.gl/issues/1515
> Initialise DeckGL layers from props

- src/components/side-panel/layer-panel/layer-configurator.js
- src/localization/ca.js
- src/localization/en.js
- src/localization/es.js
- src/localization/fi.js
- src/localization/ja.js
- src/localization/pt.js
> [Chore] Unify labels in Grid/Hex aggregation layers 

- package.json
Signed-off-by: Silvio <silvio@hivemapper.com>
> Update peer dependencies for styled-components

- docs/api-reference/README.md
> Update Map Styles Link

- src/components/common/histogram-plot.js
> [Bug] fix histogram in range

- examples/replace-component/src/app.js
- examples/replace-component/src/components/custom-layer-hover.js
- examples/replace-component/src/components/panel-toggle.js
- examples/replace-component/src/data/sample-data.js
- src/components/map/layer-hover-info.js
> [Examples] fix panel toggle exmaple, add layer hove info demo

- docs/api-reference/actions/actions.md
- src/actions/actions.js
> [Docs] fix add data to map docs

- examples/replace-component/src/app.js
- examples/replace-component/src/components/custom-map-popover.js
- examples/replace-component/src/data/sample-data.js
> [Examples] update replace-component example

- src/utils/table-utils/UPGRADE-data-container.md
- temp data container upgrade notes
> [Docs] Data container upgrade notes

- src/components/index.js
- src/components/kepler-gl.js
- src/components/map-container.js
- src/deckgl-layers/cluster-layer/cluster-layer.js
- src/layers/base-layer.js
- src/layers/point-layer/point-layer.js
- src/utils/index.js
- src/utils/layer-utils.d.ts
- src/utils/layer-utils.js
- test/browser/layer-tests/geojson-layer-specs.js
- test/helpers/layer-utils.js
- create seperate function prepareLayersForDeck and prepareLayersToRender
- fix for visibility prop
- Fix point layer text label not turned off when layer is invisible
> [Enhancement] Use layer.visible prop in deck.gl when toggle layer visibility

- src/utils/data-utils.js
Signed-off-by: Igor Dykhta <igorDykhta@users.noreply.github.com>
> [Bug] fix for long processing time of data-utils::unique

- src/layers/s2-geometry-layer/s2-geometry-layer.js
Signed-off-by: Igor Dykhta <igorDykhta@users.noreply.github.com>
> [Enhancement] s2 updateLayerMeta: push instead of spread

- src/components/bottom-widget.js
- src/components/index.js
- src/components/map-container.js
- src/components/map/layer-selector-panel.js
- src/components/map/locale-panel.d.ts
- src/components/map/locale-panel.js
- src/components/map/map-control.d.ts
- src/components/map/map-draw-panel.js
- src/components/map/map-legend-panel.js
- src/components/map/toggle-3d-button.js
- src/layers/index.js
- src/localization/cn.js
- src/utils/index.js
- test/browser/components/map/map-control-test.js
- test/helpers/mock-state.js
> [Bug] fix locale panel

- .github/workflows/build-publish-pypi.yml
- bindings/kepler.gl-jupyter/RELEASE.md
- bindings/kepler.gl-jupyter/js/package.json
- bindings/kepler.gl-jupyter/keplergl/_version.py
- update maobox token name in workflow
> [Jupyter] keplergl==0.3.2

- src/components/geocoder-panel.js
- src/components/kepler-gl.js
- src/components/side-panel/interaction-panel/tooltip-config.js
- src/utils/utils.js
- test/browser/components/kepler-gl-test.js
- test/browser/components/tooltip-config-test.js
- test/helpers/mock-state.js
- test/node/utils/index.js
- test/node/utils/kepler-gl-utils-test.js
This PR fixes the issue described here: https://github.com/keplergl/kepler.gl/issues/1659
Signed-off-by: Nikola Karaklic <nikolakaraklic@gmail.com>
> [Bug] do not display geocoder dataset in side panel

- package.json
- src/processors/data-processor.js
- src/reducers/vis-state-updaters.js
- src/utils/table-utils/kepler-table.d.ts
- src/utils/table-utils/kepler-table.js
- test/node/reducers/vis-state-test.js
> [Bug] fix pin table column overide dataset

- src/layers/cluster-layer/cluster-layer.ts
- src/layers/grid-layer/grid-layer.ts
- src/layers/hexagon-layer/hexagon-layer.ts
> [Bug]: fix grid hexbin and cluster layer crash

- src/layers/base-layer.ts
> [Bug] visual channels cannot read property 'label' of undefined

- package.json
- yarn.lock
> [Bug] Build fix

- package.json
- src/utils/observe-dimensions.ts
- yarn.lock
Signed-off-by: Mikhail Gorbachev <mikhail.gorbachev@actionengine.com>
> [Chore]: Technical: Throttle typings added

- src/components/side-panel/map-style-panel/map-layer-selector.tsx
- src/components/side-panel/map-style-panel/map-style-selector.tsx
- src/components/side-panel/panel-header-action.tsx
Signed-off-by: Mikhail Gorbachev <mikhail.gorbachev@actionengine.com>
> [Chore]: Technical: Translate components to typescript

- src/styles/base.ts
- src/styles/media-breakpoints.ts
Signed-off-by: Evgeny Zhgulev <evgeny.zhgulev@actionengine.com>
> [Chore]: Technical: add types for styled components in styles

- src/components/map/map-legend.js
Signed-off-by: Evgeny Zhgulev <evgeny.zhgulev@actionengine.com>
> fix 3d layer issue

- src/components/common/field-token.tsx
- src/constants/src/default-settings.ts
Signed-off-by: Jacob Wasilkowski <jwasilkowski@foursquare.com>
> [Chore]: FILED_TYPE_DISPLAY -> FIELD_TYPE_DISPLAY

- src/components/map-container.tsx
- src/deckgl-layers/src/cluster-layer/cluster-layer.ts
- fix z fighting for cluster layer in 3D view
- fix - render 3d building map style once
> [bug] fix for cluster layer z-fighting; fix - render 3d building map style once

- src/components/side-panel/layer-panel/layer-panel-header.tsx
- src/components/side-panel/panel-header-action.tsx
* Extend layer label editor length
* Show duplicate and delete icon over layer name
* Disable pointer event when editing layer label
https://user-images.githubusercontent.com/163940/181104550-e4eccb03-9c5d-4a7f-8782-b9d9d20ef7eb.mp4
> [Enhancement] Improve style of layer header panel

- src/components/side-panel/layer-panel/layer-column-config.tsx
> [Enhancement] disable layer column selection if empty

- src/components/side-panel/layer-panel/layer-configurator.tsx
- src/layers/src/base-layer.ts
* show dataset selector even if there is only 1 or no option
* add supportedDatasetTypes to layer
> [Bug] add supportedDatasetTypes to layer, show dataset selector even if there is only 1 or no option

- src/components/map/layer-hover-info.tsx
> [Bug] fix comparison tooltip color and position

- src/layers/src/icon-layer/icon-layer.ts
- src/reducers/index.ts
- src/reducers/vis-state-updaters.ts
- src/schemas/dataset-schema.ts
- src/schemas/schema-manager.ts
- src/utils/index.ts
[Rebase] fix types and missing import
> [Chore] fix types and missing import

- src/components/common/icons/index.tsx
- src/components/common/icons/warning-sign.tsx
- src/components/common/styled-components.tsx
- src/components/injector.tsx
- src/components/side-panel/layer-panel/layer-panel-header.tsx
> [Enhancement] render warning in layer panel header

- src/layers/src/trip-layer/trip-layer.ts
- src/layers/src/trip-layer/trip-utils.ts
> [Bug] fix trip layer timestamp check

- src/reducers/vis-state-updaters.ts
> [Bug] Fix mouse event evt.point evt.lngLat undefined crash

- package.json
- src/actions/vis-state-actions.ts
- src/components/filters/filter-panels/new-filter-panel.tsx
- src/reducers/combined-updaters.ts
- src/reducers/vis-state-merger.ts
- src/reducers/vis-state-updaters.ts
- src/utils/filter-utils.ts
- src/utils/index.ts
- src/utils/table-utils/kepler-table.ts
- test/helpers/comparison-utils.js
- yarn.lock
improve reducer updater typing
change visstate to be more relaxed
> improve reducer updater typing, change visstate to be more relaxed

- src/utils/table-utils/kepler-table.ts
- test/fixtures/test-hex-id-data.js
- test/node/reducers/vis-state-merger-test.js
- test/node/reducers/vis-state-test.js
> [feat] add type to keplerTable

- src/reducers/provider-state-updaters.ts
- src/schemas/vis-state-schema.ts
- src/utils/dom-to-image.ts
- src/utils/dom-utils.ts
- src/utils/filter-utils.ts
- src/utils/locale-utils.ts
- src/utils/table-utils/kepler-table.ts
- test/node/reducers/vis-state-merger-test.js
- test/node/schemas/vis-state-schema-test.js
* Fix map saved with empty filter cannt be load
* validate empty filter.name when merging
> [Bug] Fix map saved with empty filter cannt be load

- src/reducers/vis-state-updaters.ts
- test/helpers/comparison-utils.js
- test/node/reducers/vis-state-test.js
[Bug] rename dataset should not use spread
> [Bug] rename dataset should not use spread

- src/actions/actions.ts
- src/reducers/vis-state-updaters.ts
- src/utils/table-utils/kepler-table.ts
- test/helpers/comparison-utils.js
> [chore] test valueAccessor in field

- src/components/common/field-selector.tsx
- src/reducers/vis-state-updaters.ts
upstreaming: "chore: Updated filter-selector, item-selector, range-slider file typescript definitions"
> chore: Updated filter-selector, item-selector, range-slider file typescript definitions

- src/components/common/animation-control/playback-controls.tsx
- src/reducers/map-style-updaters.ts
- test/browser/components/common/animation-control-test.js
> [Enhancement] change export video playback button order

- src/components/geocoder/geocoder.tsx
- src/utils/filter-utils.ts
> [Enhancement] add bin to filter histogram construct

- src/components/common/icon-button.tsx
- type extension for IconButtonProps
> [chore] Export IconButton type

- src/utils/index.ts
> [Chore]: extra exports

- .github/workflows/test.yml
- src/components/index.ts
- src/components/side-panel/layer-panel/how-to-button.tsx
- src/components/side-panel/layer-panel/layer-configurator.tsx
[Chore] (Types) Add layer configurator types
- move howto button out
> [Chore] (Types) Add layer configurator types, move HowTo button out

- src/components/side-panel/layer-panel/layer-configurator.tsx
> [Fix] fix lint

- website/src/components/footer.js
> [Fix]: Kepler.gl site issue fixed

- src/components/common/item-selector/item-selector.tsx
- src/components/side-panel/common/types.ts
- src/components/side-panel/layer-panel/layer-configurator.tsx
- src/components/side-panel/layer-panel/layer-type-dropdown-list.tsx
- src/components/side-panel/layer-panel/layer-type-list-item.tsx
- src/components/side-panel/layer-panel/layer-type-selector.tsx
- src/constants/src/tooltip.ts
- src/reducers/interaction-utils.ts
- src/reducers/table-utils/kepler-table.ts
- src/utils/src/data-utils.ts
* update layer selector types
* add get length to table
* export tooltips
> [Enhancement] export layer type selector and tooltip types

- src/constants/src/tooltip.ts
- src/reducers/interaction-utils.ts
> [Enhancement] improve tooltip format label, make it more intuitive

- src/components/common/range-slider.tsx
* disable resize to avoid max depth error
* add debounce
> [Bug] Fix Range brush maximum update exceeds crashes

- src/reducers/vis-state-merger.ts
- test/node/reducers/vis-state-merger-test.js
- use correct i, preceedIdx should start with -1
- add tests
> [Bug] fix layer order not correctly reloaded

- src/layers/src/base-layer.ts
> [Bug] Fix getSampleData import

- src/reducers/vis-state-updaters.ts
> [Fix] Demo-app build fixed

- src/components/common/item-selector/item-selector.tsx
> [Fix]: Fix Item selector closeOnClickoutside conflict with portable

- src/actions/src/index.ts
- src/components/map-container.tsx
- src/components/side-panel/interaction-manager.tsx
- src/components/side-panel/interaction-panel/interaction-panel.tsx
- src/reducers/src/layer-utils.ts
- src/reducers/src/vis-state-updaters.ts
- src/types/reducers.d.ts
- src/utils/src/map-utils.ts
- test/node/reducers/vis-state-test.js
- tsconfig.json
- remove iconComponent from visState.interactionConfig to avoid reducer depends on icons
> [Chore] remove iconComponent from interactionConfig

- package.json
- src/components/src/bottom-widget.tsx
- src/components/src/common/animation-control/animation-control.tsx
- src/components/src/common/range-plot.tsx
- src/components/src/common/styled-components.tsx
- src/components/src/index.ts
- src/components/src/kepler-gl.tsx
- src/components/src/map-container.tsx
- src/components/src/map/map-control-panel.tsx
- src/components/src/map/map-legend-panel.tsx
- src/styles/src/base.ts
- src/styles/src/media-breakpoints.ts
- src/utils/src/index.ts
- src/utils/src/utils.ts
- test/browser/components/kepler-gl-test.js
- test/setup-browser-env.js
Reviewers, this upstreaming had some manually adjusted updates to account for conflicts. Although live testing of the UI seems good to me, I ask that you please double-check this one closely. Thank you.
> [Feat] mobile bottom widget styling

- src/localization/src/messages.ts
> [Chore] Refactor dynamic require

- src/components/src/map-container.tsx
- src/utils/src/index.ts
- src/utils/src/map-style-utils/mapbox-utils.ts
- test/node/utils/mapbox-utils-test.js
> [Feat] Hide Mapbox attribution when using non-Mapbox tiles

- src/components/src/common/portaled.tsx
- test/browser/components/side-panel/color-selector-test.js
> [fix]color picker crashes studio inside iframe

- src/components/src/common/animation-control/animation-control.tsx
- src/components/src/common/animation-control/playback-controls.tsx
> [Chore] Moved animation control button to the right

- src/utils/src/color-utils.ts
> [Feat] allow changing dataset color with color picker

- src/components/src/side-panel/common/dataset-title.tsx
> [Chore] onClose handler for dataset's color picker

- src/constants/src/default-settings.ts
> [Enhancement] better regex for mapbox style boundary detection

- src/layers/src/geojson-layer/geojson-layer.ts
> [Fix] [Deckgl Upgrade] properly pass opacity for linestrings

- src/components/src/common/data-table/cell-size.ts
- src/components/src/common/data-table/header-cell.tsx
- src/components/src/common/data-table/index.tsx
- src/components/src/common/data-table/option-dropdown.tsx
- src/components/src/common/histogram-plot.tsx
- src/components/src/index.ts
- src/components/src/modal-container.tsx
- src/components/src/modals/data-table-modal.tsx
- src/table/src/filter-utils.ts
- test/browser/components/modals/data-table-modal-test.js
* [Ehancement] make data-table header a factory
* add filterProps and format to colMeta
> [Feat] make data table header cell overridable 

- src/components/package.json
- src/components/src/editor/editor.tsx
- fix ts errors failing during npm release build
> [fix] fix ts issues

- .github/workflows/npmpublish.yml
> [fix] force correct npm publish version in release github action

- src/components/src/common/data-table/cell-size.ts
- src/components/src/common/data-table/header-cell.tsx
- src/components/src/common/data-table/index.tsx
- src/styles/src/base.ts
- test/browser/components/modals/data-table-modal-test.js
> [Enhancement] Add header cell stats control toggle

- src/constants/src/default-settings.ts
Signed-off-by: Xun Li <lixun910@gmail.com>
> [Fix] add time type to date field

- src/components/src/common/item-selector/dropdown-list.tsx
* fix: added title for dropdown list item
> [Fix] dropdown item title

- src/components/src/common/animation-control/animation-control.tsx
- src/components/src/common/animation-control/animation-controller.ts
> [fix] Fix timesteps based layer animation

- src/components/src/side-panel/panel-header-action.tsx
> [fix] Updated dataset item cursor style

- src/styles/package.json
Signed-off-by: Eric Peterson <git@ericp.co>
> [fix] correct @kepler.gl/styles types file location

- src/components/src/map-container.tsx
- src/layers/src/editor-layer/editor-layer-utils.ts
> [fix] Cant right click on polygon or rectangle filters to get the menu

- src/components/src/editor/editor.tsx
- src/components/src/map-container.tsx
> [fix] show filtered out and hidden layers as options in polygon filter menu

- src/components/src/common/action-panel.tsx
- src/components/src/editor/feature-action-panel.tsx
* Child support and type exports for FeatureActionPanel
* Handle null/undefined children in ActionPanel
> [chore] Child support for FeatureActionPanel

- src/layers/src/geojson-layer/geojson-layer.ts
- src/reducers/src/layer-utils.ts
> [Fix] Prevent the app from crashing on geojson layer hover

- src/components/src/map-container.tsx
* Issue: Changing the exported image resolution led to viewport changes of both the exported and the main map.
* After the fix the map viewport stays the same
> [Fix] Image export change resolution

- src/components/src/common/data-table/cell-size.ts
> [Bug] Improve render cell size script perf for data table rendering

- package.json
- src/components/src/geocoder-panel.tsx
- src/components/src/kepler-gl.tsx
- src/components/src/map-container.tsx
- src/styles/src/base.ts
- test/browser/components/geocoder-panel-test.js
* fix: open map control and geocoder for extension
> [fix] Open map control and geocoder for extension

- src/layers/src/base-layer.ts
> [fix] Icon Layer - Labels are visible even if layer is hidden

- src/layers/src/h3-hexagon-layer/h3-hexagon-layer.ts
> [Enhancement]: use dataset name as default h3 layer name

- src/components/src/common/color-legend.tsx
- src/utils/src/data-utils.ts
- src/utils/src/index.ts
- test/node/utils/data-utils-test.js
> [Enchancement] number formatting improvements

- src/components/src/map/layer-hover-info.tsx
- test/browser-headless/component/map-container-test.js
> [fix] CSS fixes to avoid conflicts with Jupyter styling when embedded without iframe

- src/components/src/side-panel/layer-panel/layer-config-group.tsx
- increase layer config group collapsible content max height, add scroll
> [Bug] Fix layer config group collapsible content overflow

- src/reducers/src/vis-state-updaters.ts
- test/node/reducers/vis-state-test.js
* fix update layer type reset layer dataId
* new layer should be add at the top
> [Bug] fix update layer type reset layer dataId, new layer at the top

- src/components/src/common/animation-control/playback-controls.tsx
- src/components/src/common/item-selector/dropdown-list.tsx
- src/components/src/common/item-selector/item-selector.tsx
- src/styles/src/base.ts
> [Enhancement] Fix dropdown list disabled color 

- src/components/src/editor/editor.tsx
- src/components/src/map-container.tsx
- src/components/src/map/map-draw-panel.tsx
> [fix] Checking if drawing is active when delete an editor feature

- src/reducers/src/vis-state-updaters.ts
> [fix] Fixed time filter toggling and display the correct filter

- src/components/src/common/action-panel.tsx
- src/components/src/common/modal.tsx
- src/components/src/common/styled-components.tsx
- src/components/src/editor/feature-action-panel.tsx
* add actionIcons to action feature panel
* better types
> [Chore]: Improve Feature action panel style 

- src/components/src/map/map-popover-content.tsx
- src/components/src/map/map-popover.tsx
* Introduce MapPopoverContent
* Fixing type and lint errors
> [Feat] Introduce MapPopoverContent (for tooltip charts)

- src/constants/src/default-settings.ts
- src/layers/package.json
- src/processors/src/data-processor.ts
- src/utils/package.json
- src/utils/src/data-utils.ts
- src/utils/src/dataset-utils.ts
- test/fixtures/geojson-style.js
- test/fixtures/geojson.js
- test/fixtures/test-csv-object.js
- test/node/utils/data-processor-test.js
- yarn.lock
- Support detect stringified object and array from csv file
- Parse object and array from string
Co-authored-by: Ilya Boyandin <ilya@boyandin.me>
> [FEAT]: add support for object and array field type

- src/components/src/common/data-table/cell-size.ts
- src/components/src/index.ts
- src/layers/src/index.ts
* Export parseGeoJsonRawFeature from utils
* disable broken browser test
> [Chore] Export parseGeoJsonRawFeature

- src/components/src/common/data-table/index.tsx
- src/components/src/modal-container.tsx
- src/styles/src/base.ts
* fix: data modal scrollbar issue
* use theme
> [Bug] data modal and data table scrollbar style

- src/reducers/src/map-state-updaters.ts
- src/types/reducers.d.ts
- src/utils/src/index.ts
- src/utils/src/projection-utils.ts
- test/node/reducers/map-state-test.js
> [feat]: Add minZoom, maxZoom, maxBounds

- src/components/src/side-panel/layer-panel/layer-config-group.tsx
Signed-off-by: hodoje <nkaraklic@foursquare.com>
> [fix] remove constant scroll around layer config group

- src/actions/src/ui-state-actions.ts
- src/components/src/common/item-selector/typeahead.tsx
- src/components/src/side-panel.tsx
- src/components/src/side-panel/layer-manager.tsx
- src/components/src/side-panel/layer-panel/add-layer-button.tsx
- src/components/src/side-panel/layer-panel/panel-view-list-toggle.tsx
- src/reducers/src/ui-state-updaters.ts
- src/types/reducers.d.ts
> [chore] changes to order layers by datasets

- src/components/src/index.ts
- src/components/src/side-panel/layer-panel/layer-type-list-item.tsx
> [Chore] export LayerTypeListItem type

- src/components/package.json
- yarn.lock
> [Chore] Update react-modal version

- src/components/src/bottom-widget.tsx
- src/components/src/kepler-gl.tsx
- src/components/src/map/map-control-panel.tsx
- src/components/src/map/map-legend-panel.tsx
* allow offset in bottom widget
> [Chore] support offset in map legend panel

- src/actions/package.json
- src/reducers/package.json
- src/reducers/src/merger-handler.ts
- src/reducers/src/vis-state-merger.ts
- src/reducers/src/vis-state-updaters.ts
- src/schemas/src/vis-state-schema.ts
- src/tasks/package.json
- src/utils/src/filter-utils.ts
- test/node/reducers/vis-state-merger-test.js
- test/node/reducers/vis-state-test.js
- yarn.lock
* upgrade react-palm
* move code to merger-handler
* handle mergeStateFromMergers
* allow merge prop as an array
* add test
* add waitToFinish prop
> [Feat] Support async mergers

- src/components/src/common/styled-components.tsx
- src/components/src/map-container.tsx
- src/components/src/types.ts
- render dataset attributions in map container
- added `showOsmBasemapAttribution` to appropriate memo deps
Co-authored-by: Jacob Wasilkowski <4933392+jwasilgeo@users.noreply.github.com>
> [Feat] render dataset attributions in map container

- src/utils/src/map-utils.ts
> [fix] fix visible layers toggle for split maps mode

- src/components/src/map/map-control-panel.tsx
- Adds disabled zoom lock text styling in addition to the existing toggle switch disabled styling.
> [feat] Improve disabled zoom lock text styling

- src/components/src/common/data-table/header-cell.tsx
-  show three dots button by default in data table
> [feat] show three dots button by default in data table

- src/utils/src/h3-utils.ts
- test/browser/layer-tests/h3-hexagon-layer-specs.js
- support Polygon and LineString mode in idToPolygonGeo
> [fix] support Polygon and LineString mode in idToPolygonGeo

- src/components/src/kepler-gl.tsx
- Use the label header component as a dragging placeholder.
> [fix] Layer drag and drop label is barely visible on light map

- src/utils/src/export-utils.ts
- add `map.info.source: kepler.gl` to export map json
> [Feat] add kepler.gl to info.source in exported kepler.gl.json

- website/src/constants.js
- website/src/content.js
- website/src/utils.js
Unfolded CDN is deprecated and we have a new one
> updated cdn from unfolded to fsq

- src/constants/src/default-settings.ts
see:
- https://github.com/keplergl/kepler.gl/pull/2461#issuecomment-1863622198
before:
after:
> add basemap thumbnails

- src/components/src/common/radius-legend.tsx
- src/components/src/index.ts
- src/components/src/map/map-legend-panel.tsx
- src/components/src/map/map-legend.tsx
- test/browser/components/map/map-legend-test.js
- Show radius legend in point layer
> [Feat] Add support for radius legend

- docs/api-reference/processors/processors.md
Update the Kepler GL Processors imports.
> Update the keplergl processors update

- bindings/kepler.gl-jupyter/js/package.json
- bindings/kepler.gl-jupyter/keplergl/_version.py
- bindings/kepler.gl-jupyter/keplergl/keplergl.py
- Fix add_data() function not working in keplergl-jupyter v0.3.4
- Release v0.3.5
> [Fix] add_data() function not working in keplergl-jupyter

- src/ai-assistant/README.md
- src/ai-assistant/package.json
- src/ai-assistant/src/components/ai-assistant-component.tsx
- src/ai-assistant/src/constants.ts
- yarn.lock
- Remove SQL plugin for AI Assistant
Will add it back later with kepler.gl duckdb plugin
> [Chore] Remove SQL plugin for AI Assistant

- bindings/kepler.gl-jupyter/js/package.json
- bindings/kepler.gl-jupyter/keplergl/_version.py
- What's included:
- [Fix] non-serializable object e.g. timestamps is not handled see https://github.com/keplergl/kepler.gl/issues/2967 and https://github.com/keplergl/kepler.gl/pull/2968
> [keplergl-jupyter] Release v0.3.7

- package.json
- yarn.lock
Tested with `yarn && yarn start`
> chore: update to hubble.gl 1.4

- docs/release-notes.md
- docs/user-guides/ai-assistant.md
- docs/user-guides/c-types-of-layers/vector.md
- docs/user-guides/sql-data-explorer.md
Added a blurb to the release notes page covering the various fixes in 3.1.1
> [docs] release notes for 3.1.1

- src/components/src/common/index.ts
- src/components/src/common/styled-components.tsx
- src/components/src/index.ts
- src/components/src/loading-indicator.tsx
- src/components/src/map-container.tsx
- src/components/src/map/map-control.tsx
- use [transiant prop](https://styled-components.com/docs/api#transient-props)
- use [withConfig](https://styled-components.com/docs/api#shouldforwardprop)
> [Bug] Fix styled-components warnings for passing props to Dom

- src/components/src/side-panel/layer-panel/vis-config-slider.tsx
- src/styles/src/base.ts
Fixes custom input
- fix ranged input when second value was ignored
- cast values from custom input to numbers if original values are numbers
- increase width of custom input to show larger values
> [fix] fixes for custom input

- src/actions/src/action-types.ts
- src/actions/src/action-wrapper.ts
- src/actions/src/actions.ts
- src/actions/src/map-state-actions.ts
- src/actions/src/vis-state-actions.ts
Update some comments in actions.
> Update Comments in actions

- src/table/src/tileset/vector-tile-utils.ts
- fix for `getFieldsFromTile` regression
> [fix] fix for getFieldsFromTile regression

- src/components/src/map/map-popover.tsx
- src/components/src/side-panel/add-by-dataset-button.tsx
- src/components/src/side-panel/filter-panel/add-filter-button.tsx
- src/components/src/side-panel/layer-panel/add-layer-button.tsx
- Side panel button auto width
- fix style typo
> [Chore] style tweak

- docs/api-reference/advanced-usages/saving-loading-w-schema.md
- docs/api-reference/advanced-usages/using-updaters.md
- docs/api-reference/cloud-providers/README.md
- src/common-utils/src/data-type.ts
- src/localization/src/locales.ts
- src/processors/src/data-processor.ts
- src/reducers/src/combined-updaters.ts
- src/reducers/src/map-state-updaters.ts
- src/reducers/src/map-style-updaters.ts
- src/reducers/src/root.ts
- src/reducers/src/ui-state-updaters.ts
- src/reducers/src/vis-state-updaters.ts
> Update old imports

- src/components/src/side-panel/layer-manager.tsx
- expose showDeleteDataset prop in LayerManager
> [chore] expose showDeleteDataset prop in LayerManager

- src/components/src/map-container.tsx
- src/components/src/plot-container.tsx
- pass through logoComponent to PlotContainer
> [chore] pass through logoComponent to PlotContainer

- src/components/src/modals/tilesets-modals/tileset-raster-form.tsx
- raster tile form - add link to docs
> [chore] raster tile form - add link to docs

- .github/SECURITY.md
ref: https://github.com/openjs-foundation/cross-project-council/pull/1588
> docs: add security escalation policy
