- src/components/common/file-uploader/file-upload.js
- src/components/common/file-uploader/upload-button.js
- src/components/common/item-selector/typeahead.js
- src/components/map-container.js
- src/components/modals/data-table-modal.js
String refs are causing an issue on Observable (see below) and have been [deprecated](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs) in React for a few years now.
The new hotness is [React.createRef](https://reactjs.org/docs/refs-and-the-dom.html#creating-refs) but I feel like we can codemod that at some point in the future if needed.
> Remove string refs from components in favor of callback-style

- src/components/common/time-range-slider.js
onChange should be updated in render() function to make TimeRangeSlider reusable
fix #99
> bugfix: TimeRangeSlider should not cache props.onChange

- examples/demo-app/src/app.js
- src/components/common/color-legend.js
- src/components/common/field-selector.js
- src/components/map/map-control.js
- src/components/map/map-legend.js
- src/components/map/map-popover.js
- src/components/side-panel/layer-panel/layer-configurator.js
- src/components/side-panel/layer-panel/layer-type-selector.js
- src/components/side-panel/layer-panel/vis-config-by-field-selector.js
- src/constants/default-settings.js
- src/deckgl-layers/cluster-layer/cluster-layer.js
- src/deckgl-layers/layer-utils/utils.js
- src/layers/aggregation-layer.js
- src/layers/base-layer.js
- src/layers/cluster-layer/cluster-layer.js
- src/layers/grid-layer/grid-layer.js
- src/layers/heatmap-layer/heatmap-layer.js
- src/layers/hexagon-layer/hexagon-layer.js
- src/layers/layer-factory.js
- src/layers/mapbox-utils.js
- src/layers/mapboxgl-layer.js
- src/utils/aggregate-utils.js
- src/utils/data-scale-utils.js
- test/fixtures/state-saved-v0.js
- test/helpers/mock-state.js
- test/node/layer-tests/heatmap-layer-specs.js
- test/node/reducers/vis-state-test.js
- test/node/utils/data-scale-utils-test.js
- Enable ordinal aggregation type `mode` and `count unique` in aggregation layer
- Added additional validation in visual channel updater to validate aggregation type and scale based on selected field
- Added more condition clause to layer visConfigSettings to render configuration selectively based on current layer config
- Specify aggregation type in layer legend and map popover 
**Hexbin aggregation by event type**
**Legend**
> [Enhancement] Enable ordinal aggregation in aggregation layer (hex, grid, cluster)

- README.md
There was some typo in the step to set `MapboxAccessToken` environment variable.
> Adding the link to get a Mapbox Access Token

- src/components/common/file-uploader/file-upload.js
Very small change to wording of the CONFIG_UPLOAD_MESSAGE to make it clear that, to upload a previous map, you have to upload a **single** JSON that contains **both** the old data and all config. 
Trying to upload separate JSONs, _which seems like a possible way forward with the old message_, in fact doesn't work and results in a map that tries to load forever.
> Change CONFIG_UPLOAD_MESSAGE to avoid confusion

- src/components/common/checkbox.js
Just noticed this while browsing through the source.  It didn't seem to make any difference either way though.
> Typo in Checkbox

- website/src/components/walkthrough.js
It looks like Chrome occasionally blocks autoplaying the walkthrough videos because of this newish policy (prevents playing unmuted videos): https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
> [website] fix video autoplay issue in Chrome

- src/components/index.js
- src/components/kepler-gl.js
- src/reducers/map-style.js
- Add default `mapStyles` to map style reducer initial state
- So that they can be customized at reducer initialization by calling `keplerGlReducer.intialState`
> [Enhancement] Add default map styles to mapStyle reducer initial state

- README.md
**Problem** - The links going out to Mapbox in the README.md file were not formatted properly. This caused you to see the Github 404 page instead of being directed to the proper Mapbox locations.
This was an easy fix and easier to test. Let me know if you all need anything else with this pull request.
> Fix broken README.md links

- examples/demo-app/src/app.js
`window.remmoveEventListener` contains a superfluous m.
> [Fix] Typo in componentWillUnmount

- src/components/map/map-legend.js
- src/layers/point-layer/point-layer.js
- Enable fp64
- Turn off depth test for text layer to avoid z-fighting
- Turn off depth test for scatterplot layer when altitude column doesn't exist
- Fix lint warning in map-legend.js (extra line)
> Fix z-fighting issue between text label and scatter plot

- src/components/side-panel/interaction-panel/interaction-panel.js
Removed non-initialized state field `innerPanelWidth` and removed the argument `width` from `ToolTipConfig` since it is not used there.
> Refactored unused & uninitialized code

- src/layers/point-layer/point-layer.js
- test/node/layer-tests/point-layer-specs.js
Fix issue #238 
Scan through all text labels to get the entire character set, and pass the character set into TextLayer.
Demo - show tree emoji in the label:
> Scan through all text labels to get the entire character set

- src/layers/heatmap-layer/heatmap-layer.js
For issue #130 👍
The main reason is that map box gl need the first color to have opacity of 0.
I added a color in the beginning of the colors array
replaced that color with rgba(0, 0, 0, 0)
> Fixing global color issue #130 for the heat map

- src/components/map-container.js
- set `transitionDuration `to 0 to avoid competing viewport updates in split maps
> [Bug] Fix Maximum call stack size exceeded when double click

- src/components/plot-container.js
- pass mapStyle to plot container which containers `threeDBuildingColor`
> [Bug] Fix missing 3d building layer in image export

- src/components/common/range-brush.js
Range brush is triggering `setFilter` whenever width changes. Slows down performance significantly during mounting, closing or opening side panel
> [Bug] Range brush width change should not trigger onBrush callback

- README.md
- examples/demo-app/src/app.js
- src/components/kepler-gl.js
- src/components/map-container.js
Adds a `getMapboxRef` prop which you can set to your custom function. That function is passed down into KeplerGl's MapContainer and is used as a callback to expose the MapContainer's `react-map-gl` [InteractiveMap](https://uber.github.io/react-map-gl/#/Documentation/api-reference/interactive-map) instance. In other words, `getMapboxRef` gives KeplerGl's parent component a reference to the inner Mapbox map.
Is this a good pattern or an anti-pattern? See my update to `examples/demo-app/src/app.js` on how it would be used.
See #268. Exposing access to the full [Mapbox GL API](https://docs.mapbox.com/mapbox-gl-js/api/) should also open a solution for #293 and #118.
Kepler.gl has powerful client-side visualizations for GeoJSON. By having access to the Mapbox GL API, developers can easily add …
> [Feat] Add getMapboxRef prop

- docs/user-guides/k-save-and-export.md
- examples/demo-app/src/actions.js
- examples/demo-app/src/app.js
- examples/demo-app/src/constants/default-settings.js
- examples/demo-app/src/reducers/index.js
- examples/demo-app/src/utils/cloud-providers/dropbox.js
- examples/demo-app/src/utils/cloud-providers/index.js
- examples/demo-app/webpack.config.js
- examples/umd-client/index.html
- examples/webpack.config.local.js
- src/actions/ui-state-actions.js
- src/components/common/icons/index.js
- src/components/common/icons/map.js
- src/components/modal-container.js
- src/components/modals/export-map-modal.js
- src/components/side-panel.js
- src/components/side-panel/panel-header.js
- src/constants/action-types.js
- src/constants/default-settings.js
- src/constants/user-guides.js
- src/reducers/ui-state-updaters.js
- src/reducers/ui-state.js
- src/styles/base.js
- src/templates/export-map.js
- website/webpack.config.js
- yarn.lock
This diff provides the feature to export current Kepler.gl Map onto a single html map with both data and configuration along with necessary javascript dependency.
This is one of the possible UX solution.
We could merge some of the export options into a single modal and use tabs or other UX elements to switch between different export capabilities.
> [Feat] Single map page

- examples/demo-app/src/factories/save-map.js
- src/components/injector.js
- src/components/modals/export-config-modal.js
- src/components/modals/export-map-modal.js
As part of the DI process we store factories in an object using the function/factory itself as key.
We noticed after code is minified we had an issue where two different components, which are part of DI chain, where returning the exactly same element.
After troubleshooting the problem we found an issue with the way we are storing factories as part of DI process. We are currently using an obj to store all factories, but we are also using factories as key. When a function is used as key, javascript calls toString() method on the function and such . value will be used as key.
During the minification process we realized both components have the same two string value: 
```
f() {return g}: 
```
a oddly coincidence.
I solved the issue by replacing the DI storage obj with an actual __Map__. The …
> Replaced DI object storage with an actual Map

- README.md
- src/components/kepler-gl.js
- src/components/map/map-control.js
- src/constants/default-settings.js
- src/constants/index.js
- src/styles/base.js
- Allow passing `theme: 'light'` to `KeplerGl` component
> [Feat] Add a light theme to KeplerGl Prop

- src/processors/data-processor.js
Add type check in geojson-processor to avoid crash when geojson contains an object in any properties. 
Signed-off-by: Matheus Monte <clark.monte1@gmail.com>
> [Bug]Solve issue #547 avoid crash application

- examples/README.md
There is an error in markdown link of the custom theme example in examples README.md
> [fix] Correct Custom Theme Example Link

- src/components/map/map-popover.js
- map popover no longer needs `isMouerOver` state to persist when user mouse over it. Now User can click on the feature to pin mouse popover
- The `hidden` class doesn't do anyting in kepler.gl, but juyter notebook css has a hidden class that prevented popover to be shown
#576
> [Bug] remove isMouseOver state from MapPopover

- bindings/kepler.gl-jupyter/setup.py
Update [the link on the pypi.org webpage](https://pypi.org/project/keplergl/) to redirect to the GitHub repo properly.
> Update link to the GitHub repo

- package.json
- src/deckgl-layers/layer-utils/cluster-utils.js
- yarn.lock
Fixes #524 (and reopens #569)
As a bonus we're now on the same version as mapbox-gl!
(@heshan0131 it looks like your jupyter commit isnt on master but was force-pushed to this branch?)
> Bump supercluster

- examples/demo-app/src/utils/cloud-providers/dropbox.js
Dropbox SDK [added a warning](https://github.com/dropbox/dropbox-sdk-js/commit/061d355da7ecafa2ce9b810825701d385dfefd78) to deprecate relying on the global `window.fetch`. This PR suppresses that warning.
> Explicitly pass window.fetch to Dropbox to suppress warning

- src/layers/base-layer.js
Fixed small logic issue in base-layer.js => registerVisConfig. The if statement checking for custom visConfig props skips over booleans with the defaultValue of 'false', evaluating the statement as falsey.
**Before**
`if (['type', 'defaultValue'].every(p => layerVisConfigs[item][p])`
**After**
`if (['type', 'defaultValue'].every(p => layerVisConfigs[item].hasOwnProperty(p))`
#644 
Signed-off-by: Harrison Hutcheon <hahman12@gmail.com>
> [Bug] Logic issue in Layer.registerVisConfig preventing custom boolean properties

- src/components/map/layer-hover-info.js
- src/constants/default-settings.js
- src/reducers/root.js
- When mint=false, kepler.gl will use the existing state instance. However, this also causes the `mapboxApiAccessToken` `mapboxApiUrl` and `mapStylesReplaceDefault` not being store in the reducer.
- We will call `keplerGlInit` on existing state as well. The `INIT` action is only listened by `map-style` reducer and is only used to store the 3 props above.
> [Enhancement] Use preserved state to apply keplerGlInit. when mint=false

- src/components/common/file-uploader/file-upload.js
- src/components/common/file-uploader/upload-button.js
- src/components/common/item-selector/typeahead.js
- src/components/common/range-brush.js
- src/components/common/range-slider.js
- src/components/common/slider/slider.js
- src/components/common/time-slider-marker.js
- src/components/kepler-gl.js
- src/components/map/map-popover.js
- src/components/plot-container.js
`createRef` is the preferred way of interacting with the DOM in React. This updates all callback refs to use the newer API.
> Switch from callback refs to createRef

- src/reducers/vis-state-updaters.js
- test/node/reducers/vis-state-test.js
- Bug: when add data with a preset config to a map that already has layers.  If `oldState.layers.length` happens to equal to `mergedState.layers.length`, kepler thinks no new layers has been merged, therefore create default layers.
- Fixe: Check if any new layers are merged from config based on new dataset id
#719 
> [Bug] check new layers based on new dataset id

- website/src/components/common/styles.js
- website/src/components/hero.js
- website/src/components/home.js
- website/src/components/policy.js
- website/src/content.js
- website/src/routes.js
Created new support policy page
> [Feat] Support Policy page

- docs/api-reference/advanced-usages/custom-mapbox-host.md
- docs/api-reference/overview.md
Adds documentation examples on replacing the default mapbox hostname & styles.
> [Docs] mapboxApiUrl usage examples

- examples/demo-app/src/actions.js
- examples/demo-app/src/utils/cloud-providers/dropbox.js
- examples/demo-app/webpack.config.js
This PR fixes: #744 
Currently, when we build the dropbox upload request we read the file name from the given blob bu unfortunately the blob name contains __":"__ as prefix.
In this PR we pass the file name to the upload method.
> [Bug] Fixed dropbox upload functionality on firefox

- src/components/index.js
Export LayerHoverInfoFactory and CoordinateInfoFactory so that minor
tweaks to MapPopover can be injected. This change allows a
CustomMapPopover injected via injectComponents to have
LayerHoverInfoFactory and CoordinateInfoFactory as deps, which is
desirable as we may want to use those components in our CustomMapPopover
as well.
> [Enhancement] Expose LayerHoverInfoFactory and CoordinateInfoFactory

- src/layers/h3-hexagon-layer/h3-hexagon-layer.js
- src/layers/h3-hexagon-layer/h3-utils.js
Similarly to how the point layer filters invalid coordinates, the H3 layer behaves strangely if given datasets that have invalid hexagon IDs (an easy test is the ID `0`).
> [Bug] Filter invalid H3 IDs

- examples/demo-app/src/actions.js
- examples/demo-app/src/utils/url.js
It won't remove the current logic, URLs must still include '.csv' and '.json' but it will allow the usage of query parameters
> [Bug] Fixed loading urls with query params

- src/constants/default-settings.js
- src/utils/aggregate-utils.js
Make use of D3 deviation and variance functions to add stdev and variance options to the list of available data aggregators.
This fails `yarn test-node`, however master also fails with the same error.
> [Feat] add stdev and variance aggregators

- examples/demo-app/src/app.js
- src/deckgl-layers/cluster-layer/cluster-layer.js
- src/deckgl-layers/layer-utils/cluster-utils.js
- src/layers/cluster-layer/cluster-layer.js
- src/layers/layer-factory.js
- test/helpers/layer-utils.js
- test/node/layer-tests/cluster-layer-specs.js
- test/node/layer-tests/index.js
- Pass mapState to deck.gl layer prop to avoid width=0, height=0 at initial rendering
- Correct reduce and map function to accumulate points in each cluster
> [Bug] fix cluster point count, cluster layer failed to render on export image

- examples/demo-app/src/app.js
- src/components/common/color-legend.js
- src/components/side-panel/layer-panel/layer-configurator.js
- src/constants/default-settings.js
- test/browser/components/common/color-legend-test.js
- test/browser/components/common/index.js
- using Sqrt, log scale in color legend causes app to crash
- Remove sqrt, log from default color aggregation for count
> [Bug] Remove sqrt, log from default color aggregation for count

- src/reducers/map-style-updaters.js
`<ColorBlock />` expects a color array (https://github.com/keplergl/kepler.gl/blob/master/src/components/side-panel/layer-panel/color-selector.js#L35) but is receiving a string, thus causing a crash.
Error:
> (bugfix) Ensure all colors returned from get3DBuildingColor are RGB arrays

- src/components/common/file-uploader/file-drop.js
> [Bug] Fix a bug in file-drop.js that causes error in server side render

- src/components/side-panel/layer-panel/layer-config-group.js
- src/components/side-panel/layer-panel/layer-configurator.js
- Geojson Layer: Do not hide height config when filll color is disabled
Before: Height config is missing when Filll color is disabled
After: Show height config but disabled it
> [Bug] Add prop.disabled to LayerConfigGroup

- src/components/injector.js
- test/browser/components/injector-test.js
- When argument is defined by spread operation. function argument length can't be determined. The check will fail regardless.
- Disable the check
> [Bug] Remove argument.length check in injector

- docs/api-reference/overview.md
In the present state, clicking on "Advanced Usage" gives a 404, advanced-usage.md doesn't exist in the parent directory either.
> Remove hyperlink with "Advanced Usage"

- src/layers/grid-layer/grid-layer.js
- src/layers/h3-hexagon-layer/h3-hexagon-layer.js
- src/layers/hexagon-layer/hexagon-layer.js
- disable wrapLongitude in geometry instance layers
- issue: https://github.com/keplergl/kepler.gl/issues/754
__Before__
__After__
> [Bug] Fix h3 layer wrap

- src/layers/base-layer.js
- use COORDINATE_SYSTEM.LNGLAT instead of COORDINATE_SYSTEM.LNGLAT_DEPR…
> [Bug] Fix low projection accuracy in higher zoom level

- .eslintrc
- .prettierrc
- contributing/DEVELOPERS.md
- package.json
- yarn.lock
As discussed in PR #334 
Kepler.gl has Prettier as a dependency for controlling coding style. However, it has not been correctly integrated and Prettiers coding style rules has because of that not been applied as intended. #334 solved this but has become outdated (it linted all files, but the files has change so much that it can no longer be merged). As agreed in the discussed in PR #334 , this PR will replace the old #334 .
This PR does a few things:
- Upgrades Prettier
- Locks the prettier version as recommend by the Prettier docs
- Correctly extend eslint
- Upgrades eslint-config-prettier
- Upgrades eslint-plugin-prettier
- Add linting information to the docs
Eslint should now mark when the programmer make code styling choices that breaks the Prettier rules.
This PR has not run the …
> [Bug] Fix prettier

- src/components/side-panel.js
- src/components/side-panel/layer-panel/layer-configurator.js
- src/layers/geojson-layer/geojson-layer.js
- test/browser/layer-tests/geojson-layer-specs.js
- test/browser/layer-tests/hexagon-layer-specs.js
- test/fixtures/state-saved-v0.js
- test/fixtures/state-saved-v1-1.js
- test/helpers/mock-state.js
> [Enhancement] Independently customize Geojson layer fill stroke opacity

- examples/demo-app/package.json
- examples/demo-app/src/cloud-providers/carto/carto-icon.js
- examples/demo-app/src/cloud-providers/carto/carto-provider.js
- examples/demo-app/src/cloud-providers/dropbox/dropbox-provider.js
- examples/demo-app/src/cloud-providers/index.js
- examples/demo-app/src/components/map-control/map-control.js
- examples/demo-app/src/reducers/index.js
- examples/demo-app/webpack.config.js
- src/components/modals/load-storage-map.js
- src/components/modals/save-map-modal.js
- src/components/modals/share-map-modal.js
- src/components/notification-panel.js
- src/components/side-panel.js
- src/reducers/map-state-updaters.js
- src/reducers/map-style-updaters.js
- website/webpack.config.js
This feature allows loading/saving private and public maps using CARTO.
Related to https://github.com/keplergl/kepler.gl/issues/804
> CARTO provider for cloud storage

- src/components/modals/image-modal-container.js
- src/components/modals/load-storage-map.js
- src/components/modals/modal-tabs.js
- src/components/modals/provider-modal-container.js
- src/components/modals/save-map-modal.js
- src/components/modals/share-map-modal.js
- test/browser/components/modals/load-data-modal-test.js
- test/browser/components/modals/load-storage-map-test.js
https://github.com/keplergl/kepler.gl/issues/990
> better handling provider tile update

- docs/keplergl-jupyter/user-guide.md
Fixed broken ***match config with data*** links in https://github.com/keplergl/kepler.gl/blob/master/docs/keplergl-jupyter/user-guide.md
> Fix broken redirects in jupyter user guide

- src/deckgl-layers/layer-utils/cpu-aggregator.js
- src/deckgl-layers/layer-utils/enhanced-bin-sorter.js
deck.gl BinSorter only properly sorts numbers. It uses '-' as it's
comparison operator. This operator returns NaN for strings which
causes the domain to be sorted randomly. We then decide if a
value is valid by comparing to the first and last elements of the
"sorted" domain which do not provide accurate bounds for string
elements. Short of making BinSorter work for multiple types, the
easiest fix is to check if a string value is in the valueDomain
of the dimensonState.
> [Bug] Fix out-of-domain coloring for valid strings

- src/reducers/vis-state-updaters.js
- src/utils/dataset-utils.js
- src/utils/table-utils/kepler-table.js
- test/node/utils/layer-utils-test.js
This has remaining one failing test case in a reducer dealing with split maps - it is a little hard to follow the logic around what it is doing there, but the error indicates that it might be trying to apply a spread operator to the class instance.
```
Failed Tests: There was 1 failure
#visStateReducer -> UPDATE_VIS_DATA.1 -> No data
✖ TypeError: Invalid attempt to spread non-iterable instance
```
> Introduce KeplerTable class

- .travis.yml
- examples/demo-app/src/app.js
- src/components/common/animation-control/animation-control.js
- src/components/common/animation-control/animation-controller.js
- src/components/common/range-brush.js
- src/components/common/range-plot.js
- src/components/common/range-slider.js
- src/components/common/slider/mouse-event.js
- src/components/common/slider/slider-bar-handle.js
- src/components/common/slider/slider-handle.js
- src/components/common/slider/slider.js
- src/components/common/time-range-slider.js
- src/components/common/time-slider-marker.js
- src/components/filters/time-widget.js
- src/components/index.js
- src/constants/default-settings.js
- src/constants/index.js
- src/styles/base.js
- src/utils/data-utils.d.ts
- src/utils/data-utils.js
- src/utils/layer-utils.d.ts
- test/browser/components/common/range-slider.js
- test/node/utils/data-utils-test.js
- manage slider animation using animation controller
- improve how handling slider drag event is handled
- support animation by preset interval and time steps
> [Enhancement] Improve animation sliders

- src/components/side-panel/panel-header.js
`PanelHeader` has a prop called `actionItems` which contains a list of actions, each with a `id`, `tooltip`, `iconComponent`, `dropDownComponent` and an `onClick` handler:
In order for the `onClick` handler to be able to dispatch actions, it needs access to the `PanelHeader`'s prop, which this PR adds.
> [Bug/Enhancement] Pass PanelHeader props to the onClick handler of action items

- src/components/map-container.js
- src/components/map/coordinate-info.js
- src/components/map/map-popover.js
**tooltip with object hover info**
**tooltip with only coordinate**
> [Feat] add zoom to coordinate tooltip

- src/actions/vis-state-actions.d.ts
- src/components/index.js
- src/components/side-panel/layer-panel/layer-config-group.js
- src/components/side-panel/layer-panel/layer-panel.js
- src/components/side-panel/layer-panel/layer-type-selector.js
- src/reducers/combined-updaters.js
- src/reducers/composer-helpers.d.ts
- src/reducers/index.js
- src/reducers/vis-state-updaters.d.ts
- src/reducers/vis-state-updaters.js
- test/node/reducers/vis-state-test.js
Add typescript types for composer helpers and export the types.
Unfortunately the generic type for `_merge` does not work, it appears that as written it is not able to deduce the full `State` type, but just the partial state which breaks further type checks.
> Add types for composer helpers

- src/components/common/file-uploader/file-drop.d.ts
- src/components/common/file-uploader/file-drop.js
- src/components/common/file-uploader/file-upload-progress.d.ts
- src/components/common/file-uploader/file-upload-progress.js
- src/components/common/file-uploader/file-upload.d.ts
- src/components/common/file-uploader/file-upload.js
- src/components/common/file-uploader/upload-button.d.ts.wip
- src/components/common/file-uploader/upload-button.js
- src/components/common/loading-spinner.js
- src/components/common/progress-bar.d.ts
- src/components/common/progress-bar.js
- src/components/common/styled-components.js
- src/components/modals/cloud-tile.js
- src/components/modals/load-data-modal.d.ts
- src/components/modals/load-data-modal.js
- test/browser/components/modals/save-map-modal-test.js
- test/node/reducers/vis-state-test.js
- tsconfig.json
- Start transitioning from prop-types to typescript types for components.
- Add typescript types to file upload components, to create a better safety net in preparation for a refactor for `upload-file.js` (planning to move logic out of component)
Signed-off-by: Ib Green <ib@unfolded.ai>
> Add typescript types for upload modal and components

- src/components/common/data-table/button.js
- src/components/common/data-table/index.js
- src/components/common/image-preview.js
- src/components/common/portaled.js
- src/components/common/switch.js
- src/components/modal-container.d.ts
- src/components/modal-container.js
- src/components/modals/add-map-style-modal.js
- src/components/modals/data-table-modal.js
- src/components/modals/delete-data-modal.js
- src/components/modals/export-map-modal/export-html-map.js
- src/components/modals/export-map-modal/export-json-map.js
- src/components/modals/export-map-modal/export-map-modal.js
- src/components/modals/share-map-modal.js
- tsconfig.json
This gets type checking flowing through the big modal-container component all the way to `upload-file.js`.
A few files look like they have big changes but I am just splitting out unmemoized components from memoized ones to ensure typescript can infer the types automatically.
> Enable modal types #1 of 2

- src/components/common/file-uploader/file-upload.d.ts
- src/components/common/file-uploader/file-upload.js
- src/components/kepler-gl.d.ts
- src/components/modal-container.js
- src/components/modals/load-data-modal.d.ts
- src/localization/ca.js
- src/localization/en.js
- src/localization/es.js
- src/localization/fi.js
- src/localization/pt.js
- src/reducers/vis-state-updaters.d.ts
- src/reducers/vis-state-updaters.js
- test/browser/components/common/file-uploader-test.js
- test/node/reducers/vis-state-test.js
Signed-off-by: Ib Green <ib@unfolded.ai>
UI and functionality now dynamically adapts if additional loaders are supplied.
`upload-file.js` should not "know about" loaders.gl objects, so placed extensions and filename extraction in modal-container - it is still part of the UI but better since seems to contain a lot of glue code and knows about a lot of things and fires of actions.
But as discussed, I should probably move the new selectors into the vis-state-reducer so that we can keep the knowledge of how to extract those things from loaders.gl loaders out of the UI.
> Load: extract extensions from loader objects

- src/processors/file-handler.js
- test/browser/file-handler.js
- test/fixtures/geojson-style.js
https://github.com/keplergl/kepler.gl/issues/1196
> [Bug] fix file handler row parsing to support single geojson feature

- docs/keplergl-jupyter/README.md
Fixed a line that was causing syntax error while saving a map on Jupyter Lab
Signed-off-by: rezw4n <rezwan490@gmail.com>
> Updated Docs for Jupyter

- src/processors/data-processor.js
- src/reducers/vis-state-updaters.js
- src/schemas/index.js
- src/schemas/vis-state-schema.js
- src/utils/index.js
> [Enhancement] export more utils and schema

- bindings/kepler.gl-jupyter/keplergl/keplergl.py
This allows to dynamically serve kepler.gl html using a web server without writing to disk like we can do with folium and flask.
https://python-visualization.github.io/folium/flask.html
````
import keplergl
import pandas as pd
import geopandas
from flask import Flask
app = Flask(__name__)
@app.route('/')
def index():
df = pd.DataFrame(
{'City': ['Buenos Aires', 'Brasilia', 'Santiago', 'Bogota', 'Caracas'],
'Country': ['Argentina', 'Brazil', 'Chile', 'Colombia', 'Venezuela'],
'Latitude': [-34.58, -15.78, -33.45, 4.60, 10.48],
'Longitude': [-58.66, -47.91, -70.66, -74.08, -66.86]})
point_gdf = geopandas.GeoDataFrame(df, geometry=geopandas.points_from_xy(df.Longitude, df.Latitude))
w1 = keplergl.KeplerGl(height=500)
w1.add_data(data=point_gdf, name="cities")
return w1._repr_html_()
if …
```
> add a _repr_html_ method like in folium

- src/components/index.js
This PR is about exporting the Typeahead component from the item-selector
> Export typeahead

- src/components/modal-container.js
- src/components/modals/export-data-modal.js
> [Enhancement] Added the ability to pass supported data types when exporting (#105)

- src/components/side-panel.js
- test/browser/components/side-panel/side-panel-test.js
- Removed CustomPanels default panels reference from SidePanel
> [Chore] SidePanel panels are now passed through props or defaults (breaking)

- src/components/geocoder/geocoder.js
- src/components/index.js
- src/localization/ca.js
- src/localization/en.js
- src/localization/es.js
- src/processors/index.js
- test/browser/components/geocoder-panel-test.js
- fixed issue when typing an incorrect address in geocoder and added ability to input coordinates
> [Bug] fixed geocoder crash and added ability to pass coordinates

- src/layers/geojson-layer/geojson-layer.js
- src/reducers/map-state-updaters.js
- src/utils/projection-utils.js
- test/node/reducers/map-state-test.js
> [Enhancement] check bounds before calling fitbounds

- bindings/kepler.gl-jupyter/keplergl/keplergl.py
- docs/keplergl-jupyter/README.md
If you pass a GeoDataFrame to Jupyter widget it gets automatically re-projected to EPSG:4326 if `crs` is set and is different. That way user does not have to worry about projections when adding data to a map.
I haven't found a test suite for Jupyter plugin, can you point me to the right place so I can write tests?
Closes #1209
> [Enhancement] automatically re-project GeoDataFrame to EPSG:4326

- src/layers/geojson-layer/geojson-layer.js
- src/layers/h3-hexagon-layer/h3-hexagon-layer.js
- src/layers/point-layer/point-layer.js
- src/layers/trip-layer/trip-layer.js
- src/utils/dataset-utils.js
- src/utils/layer-utils.js
- test/node/utils/dataset-utils-test.js
Add simple heuristic to detect a column to set the color by. Looks for first non-lat/non-lng real column.
> [Enhancement] Choose layer color by default (point layer)

- src/constants/tooltip.js
Somehow formatting for 12350 was faulty and misleading from the start
> [Bug] Fix 12350 format in tooltip

- src/components/bottom-widget.js
- src/components/common/data-table/index.js
- src/layers/arc-layer/arc-layer.js
- src/layers/base-layer.js
- src/layers/cluster-layer/cluster-layer.js
- src/layers/geojson-layer/geojson-layer.js
- src/layers/grid-layer/grid-layer.js
- src/layers/h3-hexagon-layer/h3-hexagon-layer.js
- src/layers/h3-hexagon-layer/h3-utils.js
- src/layers/hexagon-layer/hexagon-layer.js
- src/layers/hexagon-layer/hexagon-utils.js
- src/layers/icon-layer/icon-layer.js
- src/layers/index.d.ts
- src/layers/line-layer/line-layer.js
- src/layers/point-layer/point-layer.js
- src/layers/trip-layer/trip-layer.js
- src/processors/data-processor.js
- src/reducers/vis-state-updaters.js
- src/styles/base.js
- test/browser/components/injector-test.js
- Passing the correct animationFilterIdx to bottom time widget
- Fixed data table memory warning
- fix input hover style overwrite focus|active style
- fix animationconfig.domain is null causing tirp layer to crash
- check objectInfo.object in isLayerHovered
- check filter idx before setting filter property
- fix cannot read property 'group' of null when copy layer config
> [Bug] Bug fixes

- src/components/common/range-slider.js
- src/components/common/slider/slider.js
- src/utils/data-utils.d.ts
* Fixes the issue with the slider value not being clamped to the min or max accordingly when dragging the mouse outside of the range, so it was very hard to set the value to min or max of the range.
> [Bug] Clamping slider values outside range

- src/components/map-container.js
Issue #1374
This should fix the error that appears when trying to Save map to a provider (Dropbox / Carto).
The error currently happens at **MapContainer**, lin 506. The presence of `mapControls.mapDraw` is assumed, but that's not the case from this Providers > Save option flow
This small change looks enough to avoid the error and present the popup, but I'm not sure if it needs any other extra check.
> fix: save to map provider

- package.json
- yarn.lock
- Fix: Color ranges definition depends on colorbrewer.schemeGroups attribute, which isn't defined in colorbrewer v1.0.0.
> [BUG] Set colorbrewer version to 1.4.0 #1416

- package.json
- scripts/ts-smoosh/bin.js
- scripts/ts-smoosh/smoosh.js
- scripts/ts-smoosh/test.js
- scripts/ts-smoosh/tests/01-functions/a.js
- scripts/ts-smoosh/tests/02-imports/c.js
- scripts/ts-smoosh/tests/03-const/e.js
- yarn.lock
colorbrewer@1.4.0 uses broken umd module
see this issue https://github.com/saikocat/colorbrewer/issues/8
> [bug] upgrade colorbrewer to 1.5.0

- src/utils/dataset-utils.js
- test/node/utils/dataset-utils-test.js
* Choose the default field to be integer if no reals are present
* improved heuristic
* add more uuid field names
> [Enhancement] Choose the default field to be integer if no reals are present

- src/components/side-panel/layer-panel/layer-configurator.js
- src/deckgl-layers/line-layer/line-layer.js
- src/layers/line-layer/line-layer.js
- src/localization/ca.js
- src/localization/en.js
- src/localization/es.js
- src/localization/fi.js
- src/localization/pt.js
- test/node/reducers/vis-state-test.js
- test/node/utils/layer-utils-test.js
- optional elevation attribute for line layer
> [Enhancement] Support elevation in Line layer

- src/layers/icon-layer/icon-layer.js
- test/browser/layer-tests/icon-layer-specs.js
- optional elevation attribute for Icon layer
> [Enhancement] Support elevation in Icon layer

- src/utils/projection-utils.js
- test/browser/components/geocoder-panel-test.js
- test/browser/components/plot-container-test.js
- test/node/reducers/map-state-test.js
- Pass correct tileSize to mapbox.geoviewport
https://github.com/keplergl/kepler.gl/issues/1499
> [Bug] Fix center map accuracy

- src/layers/aggregation-layer.js
Fix for "Average of undefined" in Grid and Hex aggregation layers
> [Bug] fix undefined in the tooltip (Aggregation layers)

- src/components/kepler-gl.js
- src/components/modal-container.d.ts
- src/components/modal-container.js
- src/utils/export-utils.js
- use appName in exported image/html/json/data filenames
> [Feat] use appName in exported image html json map and csv data

- src/layers/base-layer.js
In current implementation when `addDataToMap` is called second time for the same `dataset.info.id`, `geojson-layer` will not  update correctly. Because `calculateDataAttribute` in GeoJSON layer require precalculated `this.dataToFeature` property which calculated in `updateLayerMeta`. So If metadata did not change (same columns but different rows), `updateLayerMeta` will not be called and layer will not update correctly.
Given that `updateLayerMeta` takes `allData` as param, it will be logical to call it when data updates.
> [Bug] Geojson layer is not updated when dataset updated

- package.json
- src/components/map-container.js
- src/components/map/layer-hover-info.js
- src/components/map/map-popover.d.ts
- src/components/map/map-popover.js
- test/browser/components/map/map-popover-test.js
- test/setup-browser-env.js
- yarn.lock
- Using Tippy to avoid complex positioning calculations. Hopefully, this will also prevent React RangeError: Maximum call stack size exceeded from happening. (BTW, I was wrong, Tippy does expose Popper's virtual element functionality, but under a different name: [getReferenceClientRect](https://atomiks.github.io/tippyjs/v6/all-props/#getreferenceclientrect), so I could use it here). Tried to keep the current tooltip behavior mostly unchanged
- A bit of a clean up of the display logic in `MapContainer`
- Tooltip positioning and overflow prevention now takes the boundaries of the container into account (`DeckGL` element)
- Improve CSS styling:
- using Flexbox instead of absolute positioning for the header row
- setting margins _between_ the children of the containers instead of before the …
> [Feat] Using tippy for map popover

- src/utils/dom-to-image.js
If map component contains images, they should be inlined as in the original dom-to-image. Only data URLs can be skipped. https://github.com/tsayen/dom-to-image/blob/master/src/dom-to-image.js#L718
The bug was introduced in https://github.com/keplergl/kepler.gl/commit/2bb3867a767f6a22a9ccc837cd5795c38013fec3#diff-32702aff9a757e2662e92aab458e2f00268c2397a3046ec69701aa6a99ad3db3L827 (expand the diff of src/utils/dom-to-image.js to see it)
> Fix screenshot with images

- bindings/kepler.gl-jupyter/keplergl/keplergl.py
- docs/keplergl-jupyter/README.md
This pull request resolves the issue https://github.com/keplergl/kepler.gl/issues/1553. By default, the User Guide URL will always be printed when a map is created. Users can set `KeplerGl(show_docs=False)` to hide the User Guide URL if needed. 
Before:
After:
> Make showing User Guide link optional for jupyter widget

- .github/workflows/build-publish-pypi.yml
- bindings/kepler.gl-jupyter/MANIFEST.in
- bindings/kepler.gl-jupyter/README.md
- bindings/kepler.gl-jupyter/RELEASE.md
- bindings/kepler.gl-jupyter/js/package.json
- bindings/kepler.gl-jupyter/js/webpack/build-html.js
- bindings/kepler.gl-jupyter/keplergl/keplergl.py
- bindings/kepler.gl-jupyter/pyproject.toml
- bindings/kepler.gl-jupyter/setup.py
1. Upgrade keplergl-jupyter widget for JupyterLab 3
2. Add build script to build keplergl-jupyter for jupyterlab separately using @jupyter/builder
3. Upgrade build script `setup.py` using jupyter_packaging library
4. Add support to Google colab (no interaction with widget because of lacking colab support). New function `show()` was proposed:
```Python
from keplergl import KeplerGl
map1 = KeplerGl()
map1.show()
```
Others
1. Add GitHub Actions “build-publish-pypi.yml” to build, test and publish (when tag release) keplergl python package to PyPI:
2. Add condo-forge/keplergl-feedstock repo: https://github.com/lixun910/staged-recipes/tree/keplergl-feedstock (transfer to keplergl org later)
```
Note:
The source tarball of keplergl in PyPi will be used to build for conda-forge automatically. …
```
> update keplergl-jupyter bindings

- src/actions/actions.d.ts
- src/components/filters/filter-panels/filter-panel-with-field-select.js
- src/components/filters/filter-panels/new-filter-panel.js
- src/components/side-panel/filter-panel/filter-panel.js
- src/reducers/vis-state-updaters.js
- src/utils/dataset-utils.js
- src/utils/filter-utils.d.ts
- src/utils/gpu-filter-utils.d.ts
- src/utils/gpu-filter-utils.js
- src/utils/index.js
- src/utils/table-utils/kepler-table.d.ts
- src/utils/table-utils/kepler-table.js
- test/browser/components/side-panel/filter-manager-test.js
- test/helpers/comparison-utils.js
Signed-off-by: Ilya Boyandin <ilyabo@gmail.com>
> [Feat] add supportedFilterTypes to dataset

- examples/demo-app/src/cloud-providers/carto/carto-provider.js
* Use DataContainers for processing data
* Request new permissions during the Oauth process
> [Bug] Fix integration with CARTO

- .github/workflows/build-publish-pypi.yml
* The current action `build-publish-pypi` throws an error at step `Publish kepler-jupyter to NPM`. See https://github.com/keplergl/kepler.gl/runs/3617500852?check_suite_focus=true
```
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/keplergl-jupyter - Not found
npm ERR! 404 
npm ERR! 404  'keplergl-jupyter@0.3.2' is not in the npm registry.
```
* According to https://github.com/npm/cli/issues/1637, adding an explicit registry URL should avoid 404 issue when publishing keplergl npm package.
* Since this error didn't impact publishing (see https://www.npmjs.com/package/keplergl-jupyter), we can test it out in the next kepler-jupyter release.
> [jupyter] Fix 404 issue when publishing keplergl npm package

- src/components/index.js
- src/components/side-panel/layer-manager.js
- src/components/side-panel/layer-panel/layer-list.d.ts
- src/components/side-panel/layer-panel/layer-list.js
- test/browser/components/side-panel/index.js
- test/browser/components/side-panel/layer-list-test.js
- test/helpers/mock-state.js
Extracts the layers list into a separate component which will help the implementation of https://github.com/keplergl/kepler.gl/issues/1658
Signed-off-by: hodoje <nikolakaraklic@gmail.com>
> [Enhancement] extract layers list to a separate component

- src/layers/base-layer.ts
I decided to use a generic class for typing settings in all classes that inherit. 
For example, this is how the "AggregationLayer" declaration will look like:
`export default class AggregationLayer extends Layer(LayerBaseConfig & LayerColorConfig & LayerSizeConfig)`
() - Must be angle brackets
> [Chore]: Technical: Setup for different Visual channels per layer

- src/deckgl-layers/svg-icon-layer/scatterplot-icon-layer.ts
- src/deckgl-layers/svg-icon-layer/svg-icon-layer.ts
> [Chore]: Technical: add types for svg-icon-layer

- src/components/common/animation-control/playback-controls.tsx
- src/components/injector.tsx
- src/components/kepler-gl.tsx
- src/components/map-container.tsx
- src/components/maps-layout.tsx
- src/reducers/map-state-updaters.ts
> [Chore]: Technical: Review fixes for pr https://github.com/keplergl/kepler.gl/pull/1790

- src/components/map/layer-hover-info.tsx
- src/utils/interaction-utils.ts
- src/utils/layer-utils.ts
- test/node/utils/interaction-utils-test.js
> [Bug] allow tooltip format to apply to aggregation layer hover

- src/components/side-panel/layer-panel/layer-panel-header.tsx
- src/components/side-panel/layer-panel/layer-panel.tsx
- src/reducers/vis-state-updaters.ts
- add allowDuplicate prop to layer header
- disable duplicate if layer is not valid
> [Bug] Disable layer copy when layer is invalid

- src/processors/src/data-processor.ts
- src/reducers/vis-state-merger.ts
- src/schemas/dataset-schema.ts
- src/schemas/index.ts
- src/schemas/schema-manager.ts
- src/schemas/schema.ts
- src/schemas/vis-state-schema.ts
- pass schema to processKelperlGlDatase
- schema manager typing
> [Enhancement] pass schema to processKeplerGlDataset

- src/actions/actions.ts
- src/schemas/index.ts
- src/utils/table-utils/kepler-table.ts
- test/fixtures/test-hex-id-data.js
- test/node/reducers/vis-state-merger-test.js
- test/node/reducers/vis-state-test.js
* add disableCreateColumn true to tile dataset
> [Enhancement] add disableDataOperation to dataset

- src/layers/src/geojson-layer/geojson-layer.ts
- src/layers/src/h3-hexagon-layer/h3-hexagon-layer.ts
- src/layers/src/point-layer/point-layer.ts
- src/layers/src/trip-layer/trip-layer.ts
- src/reducers/vis-state-updaters.ts
[Bug] fix setting layer type override layer name
Signed-off-by: Jacob Wasilkowski <jwasilkowski@foursquare.com>
> [Enhancement] set initial layer config when set layer type

- src/reducers/vis-state-updaters.ts
- test/node/reducers/vis-state-test.js
- Fix crash after layer type change
- reset clicked and hover values for a layer affected by LAYER_TYPE_CHANGE
> [BUG] Fix crash after layer type change

- src/components/map/lazy-tippy.tsx
- src/components/map/map-legend-panel.tsx
- test/browser/components/map/map-control-test.js
* use lazy tippy to improve map legend rendering perf
> [Enhancement] (Map Control) use lazy tippy to improve map legend rendering perf

- examples/demo-app/src/components/map-control/map-control.js
- src/components/map/locale-panel.tsx
- test/browser/components/map/map-control-test.js
> [Chore]: Add class names to map control

- src/components/common/item-selector/item-selector.tsx
- src/components/common/portaled.tsx
use portable and dimensionObserver in item-selector to render Dropdown
> [Enhancement] use portable in item-selector

- examples/custom-map-style/src/store.ts
- examples/custom-reducer/src/app.js
- examples/custom-reducer/src/store.js
- examples/demo-app/src/app.js
- examples/demo-app/src/cloud-providers/carto/carto-icon.js
- examples/demo-app/src/cloud-providers/dropbox/dropbox-icon.js
- examples/demo-app/src/components/banner.js
- examples/demo-app/src/components/load-data-modal/sample-maps-tab.js
- examples/demo-app/src/factories/load-data-modal.js
- examples/demo-app/src/store.js
- examples/replace-component/src/app-reducer.js
- examples/replace-component/src/components/custom-panel.js
- examples/webpack.config.local.js
- src/components/src/common/icons/index.tsx
> [Fix] "load from storage" and "Share" modals fix

- src/components/src/common/item-selector/dropdown-list.tsx
- src/components/src/common/item-selector/typeahead.tsx
- src/constants/src/default-settings.ts
- test/browser/components/common/item-selector-test.js
- test/browser/components/helpers.js
- test/setup-browser-env.js
* use infinite scroll to improve the performance of string filter on a large dataset
* add IntersectionObserver mockup for browser test; update dropdown-list for testing
> [Fix][Perf] String filter freezes browser when loading a large dataset

- src/components/src/common/index.ts
- src/components/src/index.ts
Not sure if this should be considered [fix] or not, but upgrading from 2.5.5 seems to have broke importing `<CenterFlexbox>`.
Signed-off-by: Eric Peterson <git@ericp.co>
> [fix] include CenterFlexbox in common components

- src/cloud-providers/src/provider.ts
This fixes the return type of the `downloadMap()` method in `Provider`.
It was `Promise<{ map: SavedMap; format: string }>`, but `SavedMap` itself has a `map` property. When an implementation of `downloadMap()` returns an object like `{ map: { map: { ... } }, format: ... }`, loading maps works, but the "Save"/"Save As" functionality breaks. I haven't figured out why, but I tested manually and confirmed that flattening the nested `map` property fixes the re-saving, without breaking the loading.
Signed-off-by: Eric Peterson <git@ericp.co>
> [fix] correct provider downloadMap type

- src/components/src/common/data-table/cell-size.ts
- src/components/src/common/data-table/index.tsx
- src/components/src/modals/data-table-modal.tsx
- test/browser/components/modals/data-table-modal-test.js
- Hide stats control if hasStats is falsy
- Data table adjust first cell size
> [Feat] Add hasStats prop to data table adjust first cell size

- examples/demo-app/src/cloud-providers/carto/carto-provider.js
When running the project locally via `npm start`, the below error is produced. This changes fixes that error so the demo website builds and serves locally.
```
ERROR in ./src/cloud-providers/carto/carto-provider.js
Module not found: Error: Can't resolve 'reducers' in '/Users/ericp/epeterson320/kepler.gl/examples/demo-app/src/cloud-providers/carto'
@ ./src/cloud-providers/carto/carto-provider.js 40:0-37 477:17-26
@ ./src/cloud-providers/index.js
@ ./src/app.js
@ ./src/main.js
```
Signed-off-by: Eric Peterson <git@ericp.co>
> [fix] fix import in demo-app carto provider

- src/components/src/editor/feature-action-panel.tsx
Moves FeatureActionPanel to the class component to work with react-onclickoutside. We were using onClickOutside incorrectly in FeatureActionPanelFactory - it's not intended to support functional components (fails in esbuild)
> [fix] Move FeatureActionPanel to class component

- src/components/src/common/data-table/cell-size.ts
- src/components/src/common/data-table/grid.tsx
- src/components/src/common/data-table/index.tsx
- src/components/src/common/field-token.tsx
- src/components/src/modals/data-table-modal.tsx
- src/styles/src/base.ts
- test/browser/components/modals/data-table-modal-test.js
* Smarter cell size calculator so header cell can be shown in full, a cell doesn't expand too wide
* Hide double scroll bar
* Prevent scroll left from triggering navigation change
> [Enhancement] Render data table with smarter cell size, prevent scroll back

- src/reducers/src/map-style-updaters.ts
- Fixes automatic background color selection when switching to "No Basemap" from a basemap that has a mapbox "interpolate" color for the background layer.
> [fix] improves handling of "interpolate" mapbox colors during basemap switching

- src/components/src/common/styled-components.tsx
- src/components/src/map-container.tsx
- src/components/src/types.ts
- replaced datasets attributes css `width` with `max-width`
- added space between basemap attribution & dataset attributions
> [Fix] Datasets attribution width styling

- src/components/src/common/styled-components.tsx
- src/components/src/map-container.tsx
- src/components/src/types.ts
- replaces margin space with `|` between dataset attributions & basemap attributions
> [Fix] Datasets and basemap attributions separated by "|"

- src/actions/src/vis-state-actions.ts
- src/reducers/src/combined-updaters.ts
- src/reducers/src/vis-state-merger.ts
- src/reducers/src/vis-state-updaters.ts
- src/schemas/src/index.ts
- src/schemas/src/schema-manager.ts
- src/schemas/src/vis-state-schema.ts
- src/types/actions.d.ts
- src/types/reducers.d.ts
- src/types/schemas.d.ts
- src/types/types.d.ts
- src/utils/src/filter-utils.ts
- test/node/reducers/vis-state-test.js
Add a MinSavedConfigV1 type to describe minimum config required to load the map
Export more Config types
> [Chore] Add more types for schema

- src/utils/src/data-utils.ts
- src/utils/src/index.ts
- test/node/utils/data-utils-test.js
round a giving number at most 4 decimal places, e.g.
10 -> 10
1.12345 -> 1.2345
1.123455 -> 1.2346
2.0 -> 2
1.00005 -> 1.0001
> [Fix] round the float number to up to 4 decimal places in table

- src/components/src/common/icons/cursor-point.tsx
- src/components/src/common/icons/index.tsx
- src/components/src/map-container.tsx
- src/components/src/map/layer-hover-info.tsx
- src/components/src/map/map-popover.tsx
- src/layers/src/editor-layer/editor-layer-utils.ts
- test/browser-headless/component/map-container-test.js
- test/browser/components/map/map-popover-test.js
- test/helpers/mock-state.js
The basic idea is to extend the current map selection toolset so that users can do more with mouse selection.
> [Feat] enhance mouse selection toolset

- src/reducers/src/map-state-updaters.ts
- prevent the passing of undefined values to Kepler state in `updateViewport`
> [fix] handle undefined values in updateViewport

- src/components/src/index.ts
- src/components/src/map/map-control-panel.tsx
- src/components/src/map/map-legend-panel.tsx
- src/reducers/src/map-state-updaters.ts
- Adds optional isViewportUnsyncedAllowed component prop that defaults to true in MapControlPanel and MapLegendPanel.
> [fix] Improved split+unsynced mode for better handling

- src/components/package.json
- src/components/src/dnd-layer-items.ts
- src/components/src/kepler-gl.tsx
- src/components/src/map-container.tsx
- src/components/src/side-panel/layer-panel/dataset-section.tsx
- src/components/src/side-panel/layer-panel/layer-list.tsx
- src/components/src/side-panel/layer-panel/layer-panel-header.tsx
- src/components/src/side-panel/layer-panel/layer-panel.tsx
- src/reducers/src/vis-state-updaters.ts
- src/utils/src/split-map-utils.ts
- test/helpers/mock-state.js
- test/node/reducers/vis-state-test.js
- yarn.lock
1. replace [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) with [dnd-kit](https://github.com/clauderic/dnd-kit). React-sortable-hoc is no longer actively maintained and its developers strongly encourage new consumers to adopt dnd-kit instead of adopting react-sortable-hoc.
2. Add support for the split map mode, allowing dragging and dropping layers from the side panel to each of the two map panels.
> [Feat] Drag and drop interaction for split map

- src/layers/src/arc-layer/arc-layer.ts
- src/layers/src/cluster-layer/cluster-layer.ts
- src/layers/src/geojson-layer/geojson-layer.ts
- src/layers/src/grid-layer/grid-layer.ts
- src/layers/src/h3-hexagon-layer/h3-hexagon-layer.ts
- src/layers/src/hexagon-layer/hexagon-layer.ts
- src/layers/src/icon-layer/icon-layer.ts
- src/layers/src/point-layer/point-layer.ts
- Add visible property to the hover layer that is tied to its main layer's visibility. This ensures that turning off the visibility of a layer will also hide any pinned map popover that has a highlight layer on the map, too.
> [Fix] hide pinned selection outline when layer is hidden

- src/components/src/common/data-table/grid.tsx
- src/reducers/src/vis-state-merger.ts
- src/reducers/src/vis-state-updaters.ts
- test/helpers/mock-state.js
- test/node/reducers/vis-state-merger-test.js
- test/node/reducers/vis-state-test.js
This PR ensures we load the layer correctly when using `createLayerFromConfig`. We can now pass a parsed and loaded layer to the method
> [feat] Create layer correctly from saved layer config

- src/components/src/common/histogram-plot.tsx
- fix E.g. The loaded data has datetime column within one day. However, when specify Interval “24 hours”, the blue area in the selection area is rendered incorrectly outside.
> [Fix] intervals rendered incorrectly in time widget

- src/components/src/kepler-gl.tsx
- When dropping an existing layer to the same map again, the layer shouldn't toggle to invisible. This fix is to solve this issue.
> [Fix] Drop the same layer multiple times to one map

- src/components/src/common/checkbox.tsx
- src/components/src/common/data-table/grid.tsx
- src/reducers/src/combined-updaters.ts
- src/reducers/src/composers.ts
- src/reducers/src/ui-state-updaters.ts
- test/browser/components/map/map-control-test.js
- test/node/reducers/root-test.js
- Auto-display legend panel in split mode
- fix legend panel bug: in split map, with the left legend panel open, click close-btn two times to close the panel
- fix layer panel bug: click radio two times to close/open a layer
> [Fix] Auto-display legend in split mode + Fix legend and layer panel bugs

- src/actions/src/vis-state-actions.ts
- src/components/src/common/data-table/display-format.tsx
- src/components/src/common/data-table/header-cell.tsx
- src/components/src/common/data-table/index.tsx
- src/components/src/common/data-table/option-dropdown.tsx
- src/components/src/common/field-selector.tsx
- src/components/src/index.ts
- src/components/src/map/layer-hover-info.tsx
- src/components/src/modals/data-table-modal.tsx
- src/components/src/side-panel/interaction-manager.tsx
- src/components/src/side-panel/interaction-panel/interaction-panel.tsx
- src/components/src/side-panel/interaction-panel/tooltip-config.tsx
- src/components/src/side-panel/interaction-panel/tooltip-config/tooltip-chicklet.tsx
- src/reducers/src/interaction-utils.ts
- src/reducers/src/vis-state-updaters.ts
- src/types/components.d.ts
- test/browser/components/modals/data-table-modal-test.js
- test/browser/components/tooltip-config-test.js
- test/node/utils/interaction-utils-test.js
Add a global “display formatter” that will be used to format the numeric and date-time values.
This global fomatter will be used as a “default formatter”, so users can set up and enable/disable the display format quickly. Besides, users will be able to customize the display format for each component on top of the global formatter (e.g. customize the display format for each column in the data table)
* Table View
* User can set display format for all integer/float/date columns at once
* User can overwrite display format for each column
* Tooltip
* Use field.displayFormat instead of visState.interactionConfig.tooltips
* User can overwrite display format for each field
> [Feat] Add display format setting for table/tooltip

- src/reducers/src/vis-state-merger.ts
- test/node/reducers/vis-state-test.js
- when user create a layer by calling addLayer(config), kepler will allow columns to be undefined
> [Enhancement] Allow empty column when layer created from config

- test/helpers/layer-utils.js
- modify testing layer utils to be more flexible about creating layers from specific classes instead of only allowing usage of predefined Kepler layer classes
> [chore] layer testing support

- src/components/src/common/animation-control/animation-controller.ts
- In time widget animation, the last time filter has not been applied and "played" on the map
> [Fix] time widget animation: apply same duration for last time filter

- src/components/src/side-panel/layer-panel/color-selector.tsx
- improve type for <ColorBlock> component and add default background color if the color prop array is missing
> [Fix] ColorBlock component TypeError: e.color.slice(...).join is not a function

- src/schemas/src/vis-state-schema.ts
- test/helpers/mock-state.js
- check for column existence to avoid TypeError: Cannot read properties of undefined (reading 'value')
> [Fix] vis state schema column save undefined typeerror

- examples/demo-app/src/cloud-providers/foursquare/foursquare-provider.js
- examples/demo-app/webpack.config.js
- examples/webpack.config.local.js
- src/components/src/modals/cloud-tile.tsx
- src/components/src/modals/save-map-modal.tsx
- webpack/shared-webpack-configuration.js
- website/src/reducers/analytics.js
- website/webpack.config.js
The website webpack configuration was loading kepler.gl files node_modules rather than local src files.
This PR makes sure the correct aliases (copied from examples webpack config) are used.
I combined several webpack configuration variables into one shared file
> [fix] Fixed website configuration to correctly import local kepler files

- examples/demo-app/src/actions.js
- examples/demo-app/src/cloud-providers/carto/carto-provider.js
- examples/demo-app/src/cloud-providers/dropbox/dropbox-provider.js
- examples/demo-app/src/cloud-providers/foursquare/foursquare-provider.js
- examples/demo-app/src/cloud-providers/index.js
- src/cloud-providers/src/index.ts
- src/cloud-providers/src/provider.ts
- src/components/src/modals/cloud-tile.tsx
This PR fixe:
- issue with provider tile fetching login
- issue when loading a map from a provider and updating the URL
> Fix cloud tile fetching logic

- examples/webpack.config.local.js
- package.json
- webpack/shared-webpack-configuration.js
The new GeoArrow sample seems not working on kepler.gl site. From the log, it seems different `apache-arrow` modules have been used and caused the error. This PR tries to fix this.
> [Fix] GeoArrow demo not working

- examples/node-app/webpack.config.js
Trying to run the `node-app` example fails with import errors like this:
```
ERROR in ./node_modules/apache-arrow/ipc/metadata/message.mjs 46:14-33
Can't import the named export 'Builder' from non EcmaScript module (only default export is available)
@ ./node_modules/apache-arrow/Arrow.mjs
@ ./node_modules/apache-arrow/Arrow.dom.mjs
@ ./node_modules/@kepler.gl/utils/dist/arrow-data-container.js
@ ./node_modules/@kepler.gl/utils/dist/index.js
@ ./node_modules/@kepler.gl/components/dist/side-panel/layer-panel/layer-list.js
@ ./node_modules/@kepler.gl/components/dist/index.js
@ ./src/app.js
@ ./src/main.js
```
Copying this fix from the `demo-app` resolves them:
https://github.com/keplergl/kepler.gl/blob/f897057379e4c5483fd3cfe788036e71d791dbaa/examples/demo-app/webpack.config.js#L40-L45
> [Fix] Example node-app Arrow Errors

- README.md
- docs/api-reference/actions/actions.md
- examples/demo-app/src/app.js
- src/actions/src/vis-state-actions.ts
- src/utils/src/projection-utils.ts
- test/browser-headless/component/map-container-test.js
- test/browser/components/map-container-test.js
In the process of #2495 I ran across some react-map-gl broken links. I changed the readme to link to MapLibre as well. There are many more references to mapbox, including public interfaces, I didn't touch.
> (chore) Update docs to react-map-gl v7

- src/components/src/dnd-context.tsx
- src/components/src/side-panel/layer-manager.tsx
- src/components/src/side-panel/layer-panel/dataset-layer-group.tsx
- src/components/src/side-panel/layer-panel/dataset-layer-section.tsx
- src/components/src/side-panel/layer-panel/layer-list.tsx
- src/components/src/side-panel/layer-panel/layer-panel-header.tsx
- src/components/src/side-panel/layer-panel/layer-panel.tsx
- src/localization/src/translations/cn.ts
- src/localization/src/translations/en.ts
- test/browser/components/side-panel/layer-list.spec.js
- test/browser/components/side-panel/layer-manager-test.js
- test/browser/components/side-panel/layer-panel-header-test.js
- test/browser/components/side-panel/side-panel-test.js
Add a zoomtolayer PanelAction in the component of layer-panel-header. (The icon is temporarily using filterFunnel, and a scaling icon will need to be designed later)，Then, import MapStateActions.fitBounds in the parent components and write function **onZoomToLayer**：`    _zoomToLayer: MouseEventHandler = e => {
e?.stopPropagation();
const bounds = this.props.layer?.meta?.bounds;
bounds && this.props.zoomToLayer(bounds);
};
`
Support #2446
> [Feat]Support Zoom to layer in layer panel

- contributing/DEVELOPERS.md
Updates the contributing guide to match the `package.json#engines` requirement:
https://github.com/keplergl/kepler.gl/blob/4932e76acf37167481df6b222e293c16d78af2c5/package.json#L260-L262
> [Docs] Update Node.js version in contributing guide to v18

- bindings/kepler.gl-jupyter/js/lib/keplergl/components/app.js
The Helmet component injects a new <title> for the page when the jupyter component renders. I'm guessing it's not the intention to take over the page title of a notebook.
Signed-off-by: Jack Amadeo <jamadeo@gmail.com>
> jupyter widget: don't take over <title>

- bindings/kepler.gl-jupyter/README.md
- bindings/kepler.gl-jupyter/js/package.json
- bindings/kepler.gl-jupyter/pyproject.toml
- bindings/kepler.gl-jupyter/requirements.txt
- docs/keplergl-jupyter/README.md
Get ready to tag keplergl 0.3.4-alpha release.
- Update dependencies
- Update docs
- Update version number
Note: For https://github.com/keplergl/kepler.gl/pull/2545, I did a test and noticed that the current implementation doesn't work with the latest ipywidgets 8.1.2. Therefore, the ipywidgets is still pinned to 7.8.1
> [Release] Kepler-Jupyter 0.3.4 alpha release

- .eslintrc
- .prettierrc
- .prettierrc.js
- actions.js
- babel.config.js
- bindings/kepler.gl-jupyter/keplergl/keplergl.py
- cloud-providers.js
- components.js
- constants.js
- effects.js
- examples/webpack.config.local.js
- jest.config.js
- jest.setup.js
- layers.js
- localization.js
- middleware.js
- package.json
- processors.js
- reducers.js
- schemas.js
- src/components/src/modals/save-map-modal.spec.tsx
- styles.js
- test/browser/components/injector-test.js
- utils.js
- yarn.lock
- Fix jest test by importing loader.gl/polyfill from esm
- Fix browser jsdom test by importing loaders.gl/polyfill from esm
- Import @kepler.gl src in test
- delete unused files
- Update jsdom
> [Chore] fix tests

- examples/demo-app/esbuild.config.mjs
The "assert" was removed in NodeJS 22. Instead "with" should be used. This was added in v17.1.0, v16.14.0.
https://nodejs.org/docs/latest-v22.x/api/esm.html#import-attributes
> Replaced deprecated "assert" with "with"

- examples/demo-app/yarn.lock
- src/reducers/src/export-utils.ts
- src/utils/src/application-config.ts
- src/utils/src/export-utils.ts
- src/utils/src/index.ts
* Application config
* Update kepler-gl.tsx
* Trying to fix failing tests
* Move applicationConfig to separate file to avoid test errors
* Revert "Trying to fix failing tests"
This reverts commit 1ee283aaa9b24fe968928ceb673402c35a022a71.
* Moving export to the end
* Adding missing dependency
* Comment and more explicit export
* Try to fix import errors
* Remove unnecessary change
* Moved applicationConfig to utils in another attempt to avoid errors in CI
* Reorg
> [Chore] Adding application config

- src/components/src/common/radius-legend.tsx
- src/components/src/map-container.tsx
- src/components/src/modals/add-map-style-modal.tsx
- src/components/src/plot-container.tsx
- src/components/src/side-panel/layer-panel/layer-column-mode-config.tsx
- src/layers/src/arc-layer/arc-layer.ts
- src/layers/src/base-layer.ts
- src/layers/src/geojson-layer/geojson-layer.ts
- src/layers/src/geojson-layer/geojson-utils.ts
- src/layers/src/mapboxgl-layer.ts
- src/layers/src/trip-layer/trip-layer.ts
- src/utils/package.json
- src/utils/src/application-config.ts
- src/utils/src/index.ts
- yarn.lock
> [Feat] Dynamic map lib config

- bindings/kepler.gl-jupyter/js/package.json
- bindings/kepler.gl-jupyter/keplergl/_version.py
- bindings/kepler.gl-jupyter/keplergl/keplergl.py
Revert the changes (which is probably added accidentally) in add_data() function from https://github.com/keplergl/kepler.gl/pull/2565/files#diff-9ad9c902c565677c69bdfc9666ed0fbfd12155854bd4339663e09bd475366ca1L143
Update version to 0.3.6
> [Fix] Problems to add data to maps through python code in kepler-jupyter

- examples/demo-app/README.md
> [Misc] Update demo-app README.md

- examples/demo-app/package.json
- examples/demo-app/yarn.lock
- src/ai-assistant/package.json
- src/ai-assistant/src/components/ai-assistant-config.tsx
- src/ai-assistant/src/config/models.json
- yarn.lock
- Add options to select DeepSeek models
- Add timer to monitor initial model connection
> [Chore] Add DeepSeek in Ai Assistant

- docs/user-guides/c-types-of-layers/vector.md
Using the vector tile page to test two implementations of remote mp4 embedding with gitbook.
> [docs]: testing mp4 embed with gitbook

- bindings/kepler.gl-jupyter/keplergl/keplergl.py
addresses https://github.com/keplergl/kepler.gl/issues/2967
I tested the MRE in the issue above locally and it works. Would probably be good to have handlign for other non-JSON serializable types as well.
I didn't find the root cause for why this wasn't an issue in earlier widget versions so I opted to make this type handling change in `_df_to_dict`. Let me know if you think there would be a better place to do this handling.
> convert datetimes to str so they can convert to json

- src/ai-assistant/src/components/ai-assistant-component.tsx
Fix #2984
**Description**
This PR fixes a bug where the AI Assistant incorrectly sends chat messages to `127.0.0.1:11434` instead of the configured Ollama Base URL. The issue occurs after the chat stream initializes correctly, but subsequent chat messages are sent to localhost.
> [fix] AI Assistant sends messages to 127.0.0.1 instead of remote Ollama URL (keplergl#2984)

- src/utils/package.json
- yarn.lock
When using in a vite app and when using pnpm the dev server Fails to resolve import "mapbox-gl.  Possibly, because pnpm is more strict about dependencies. Adding the dependency directly to the app doesn't help.
> Add mapbox-gl dep to prevent Failed to resolve import in vite

- src/components/src/modals/export-image-modal.tsx
- src/components/src/plot-container.tsx
- src/effects/src/effect.ts
- src/types/effects.d.ts
For #3034 
- fix for image export with active effects
> [fix] fix for image export with effects

- src/table/src/kepler-table.ts
For #3094 
- Fixed tooltip crash for the Trip Layer.
- The Trip Layer calculates intermediate data between two data points and sends a materialized row as an array to data accessors, which by default expect an index and a data container.
> [fix] fix tooltip crashing for trip layer

- src/components/src/loading-indicator.tsx
- src/components/src/map-container.tsx
- src/layers/src/index.ts
- src/layers/src/raster-tile/raster-tile-layer.ts
- src/reducers/src/layer-utils.ts
- The loading indicator is now shown for the Vector Tile layer.
- After each deck.gl render, check the state of the layers to determine if any are still loading.
- Display the number of loaded raster tiles.
> [feat] loading indicator improvements

- src/constants/src/default-settings.ts
- src/deckgl-layers/src/raster/raster-mesh-layer/raster-mesh-layer-webgl2.vs.ts
- src/deckgl-layers/src/raster/raster-mesh-layer/raster-mesh-layer.ts
- src/layers/src/raster-tile/image.ts
- src/layers/src/raster-tile/raster-tile-layer.ts
- src/layers/src/raster-tile/types.ts
- src/reducers/src/layer-utils.ts
> [fix] fixes for raster tile layer

- src/components/src/side-panel/layer-panel/custom-picker.tsx
- When using SketchPicker, the parent component CustomPicker can potentially be invoked from ReactDOM as a function without any props.
> [fix] Custom picker fix when called during initialization

- src/duckdb/src/components/sql-panel.tsx
- src/duckdb/src/table/duckdb-table-utils.ts
- src/duckdb/src/table/duckdb-table.ts
- add cast from BigInt to Double by default in DuckDB mode
> [fix] DuckDB - cast BigInts to Double by default

- src/ai-assistant/src/constants.ts
Remove the incorrect spatial join instruction from system instruction. There is already a description for spatial join tool: https://github.com/GeoDaCenter/openassistant/blob/15644ac2327e9b6b0d42765f0c5cff446750af8f/packages/tools/geoda/src/spatial_join/tool.ts#L105
> [fix] update spatial join instruction

- src/components/src/modals/tilesets-modals/load-tileset.tsx
- src/components/src/modals/tilesets-modals/tileset-wms-form.tsx
- src/constants/src/layers.ts
- src/deckgl-layers/src/index.ts
- src/deckgl-layers/src/wms/wms-layer.ts
- src/layers/src/index.ts
- src/layers/src/wms-layer/wms-layer-icon.tsx
- src/layers/src/wms-layer/wms-layer.ts
- src/utils/src/application-config.ts
- updated icon
- export icon properly
- save bounding box and zoom to bounds
- check for name if title is missing
- remove from EDITOR_AVAILABLE_LAYERS
- transparent by default
- custom deck wms layer - just started
> [fix] WMS layer fixes 1

- src/reducers/src/map-state-updaters.ts
- src/utils/src/projection-utils.ts
- test/browser/components/geocoder-panel-test.js
- test/browser/components/plot-container-test.js
- test/node/reducers/map-state-test.js
Before this fix, the initial zoom levels for the basemap and Deck layers could differ, requiring user input to synchronize the projections. This issue affected any layer whose bounds included latitude values closer the poles.
- getCenterAndZoomFromBounds - add extra zoom logic from normalizeViewportProps
- width was used instead of height
Example how dataset looked right after loading before the fix:
After the fix:
> [fix] fit to bounds - fix initial basemap and deck projections mismatch

- src/duckdb/src/table/duckdb-table-utils.ts
- test/node/utils/duckdb-utils-test.js
- test/node/utils/index.js
#3153
- fix for space in column name
- fix for complex table names that are already quoted
- tests for duckDB utils
> [fix] DuckDB mode: space in column name breaks file import (#3153)

- src/duckdb/src/index.ts
- src/duckdb/src/processors/data-processor.ts
- Add `duckDBColumnType` calculation for datasets saved without native DuckDB type information (examples)
- Export DuckDB-related utilities
> [feat] export duckdb column logic

- src/components/src/side-panel/layer-panel/color-scale-selector.tsx
- the crash happens when the accessor returns numeric-looking strings. d3-histogram treats it as numeric, computes a bad domain/thresholds and ends up with an “Invalid array length”.
> [fix] fix for a crash in getBins when numeric strings are treated as numbers

- src/components/package.json
- yarn.lock
Update the types so that we are not getting this error:
> Update react-modal types version

- src/components/src/modal-container.tsx
- src/table/src/tileset/vector-tile-utils.ts
- add support for boolean filter in vector tiles
- we don't perform cpu-side filtering for tiles, so transform boolean range to 0-1 range for direct GPU support
> [feat] add support for boolean filter in vector tiles

- src/components/src/common/color-legend.tsx
- src/components/src/map/map-legend-panel.tsx
- src/components/src/map/map-legend.tsx
- src/components/src/plot-container.tsx
for #3174 
- move _revert_ icon left to prevent bottom scrollbar from appearing / cutout by the right side of the legend
- ellipsis for long values
- fix for legend positioning during image export
- hide any legend scrollbars during image export
> [fix] fixes for legend

- src/layers/src/vector-tile/common-tile/tile-dataset.ts
- src/layers/src/vector-tile/vector-tile-layer.ts
For #3012 
- in vector tile layer rely on built in `highlightedFeatureId` for hovering
- add more props for unique id 
- smart outline calculation for features that are in multiple tiles
Before:
After:
> [fix] vector tile layer - use highlightedFeatureId for hover

- docs/release-notes.md
- Add missing release notes for 3.2
> [chore] Add missing release notes for 3.2
